from tests.hybrid_account_fixture import *


class HybridAccountDashboardUiCases:
    def test_ui_separates_graphics_and_hides_toggle_controls(self):
        import inspect
        from fastapi.testclient import TestClient
        import main

        client = TestClient(main.app)
        page = client.get("/").text
        css_response = client.get("/ui/dashboard.css")
        app_response = client.get("/ui/app.js")
        api_response = client.get("/ui/runtime/api.js")
        status_response = client.get("/ui/runtime/status.js")
        account_status_response = client.get("/ui/runtime/accountStatus.js")
        table_response = client.get("/ui/components/accountsTable.js")
        feedback_response = client.get("/ui/components/feedback.js")
        icons_response = client.get("/ui/components/icons.js")
        bindings_response = client.get("/ui/events/bindings.js")
        settings_response = client.get("/ui/panels/settingsPanels.js")
        js_response = client.get("/ui/app/dashboard.js")
        kanit_regular_response = client.get("/ui/fonts/Kanit-Regular.ttf")
        kanit_medium_response = client.get("/ui/fonts/Kanit-Medium.ttf")
        kanit_license_response = client.get("/ui/fonts/OFL.txt")
        self.assertEqual(css_response.status_code, 200)
        self.assertEqual(app_response.status_code, 200)
        self.assertEqual(api_response.status_code, 200)
        self.assertEqual(status_response.status_code, 200)
        self.assertEqual(account_status_response.status_code, 200)
        self.assertEqual(table_response.status_code, 200)
        self.assertEqual(feedback_response.status_code, 200)
        self.assertEqual(icons_response.status_code, 200)
        self.assertEqual(bindings_response.status_code, 200)
        self.assertEqual(settings_response.status_code, 200)
        self.assertEqual(js_response.status_code, 200)
        self.assertEqual(kanit_regular_response.status_code, 200)
        self.assertEqual(kanit_medium_response.status_code, 200)
        self.assertEqual(kanit_license_response.status_code, 200)
        self.assertGreater(len(kanit_regular_response.content), 100000)
        self.assertGreater(len(kanit_medium_response.content), 100000)
        self.assertIn("SIL OPEN FONT LICENSE", kanit_license_response.text)
        def load_css_bundle(path: str, seen=None) -> str:
            seen = seen or set()
            if path in seen:
                return ""
            seen.add(path)
            response = client.get(path)
            self.assertEqual(response.status_code, 200)
            text = response.text
            parts = []
            cursor = 0
            for match in re.finditer(r'@import\s+url\("([^"]+)"\);', text):
                parts.append(text[cursor:match.start()])
                href = match.group(1)
                if href.startswith("./"):
                    base_path = path.split("?", 1)[0].rsplit("/", 1)[0]
                    href = f"{base_path}/{href[2:]}"
                parts.append(load_css_bundle(href, seen))
                cursor = match.end()
            parts.append(text[cursor:])
            return "\n".join(part for part in parts if part)

        css = load_css_bundle("/ui/dashboard.css")
        js = "\n".join([
            app_response.text,
            api_response.text,
            status_response.text,
            account_status_response.text,
            table_response.text,
            feedback_response.text,
            icons_response.text,
            bindings_response.text,
            settings_response.text,
            js_response.text,
        ])
        html = page + "\n" + css_response.text + "\n" + css + "\n" + js
        def normalize_css_fragment(value: str) -> str:
            return re.sub(r";}", "}", re.sub(r"\s+", "", value))

        compact_css = normalize_css_fragment(css)
        assert_css_contains = lambda snippet: self.assertIn(normalize_css_fragment(snippet), compact_css)
        self.assertEqual(main.app.title, "Cronus Launcher")
        self.assertIn("<title>Cronus Launcher</title>", html)
        self.assertIn('<link rel="icon" type="image/png" href="/ui/cronus-favicon.png">', page)
        self.assertIn('<meta name="cronus-api-token" content="', page)
        self.assertIn(main.INSTANCE_TOKEN, page)
        self.assertIn('<link rel="stylesheet" href="/ui/dashboard.css?v=limiter-single-action">', page)
        self.assertIn('<script type="module" src="/ui/app.js?v=developer-copy-no-hang"></script>', page)
        self.assertIn("import './app/dashboard.js?v=developer-copy-no-hang';", js)
        self.assertIn("export async function api", js)
        self.assertIn("export function createStatusRuntime", js)
        self.assertIn("export function healthSeverity", js)
        self.assertIn("health.ok===false", js)
        self.assertIn("return 'danger'", js)
        self.assertIn("export function rowStatusLabel", js)
        self.assertIn("statusLabel=rowStatusLabel(a,b)", js)
        self.assertIn("statusLabel==='Waiting For Lua'?`${b} lua`:b", js)
        self.assertIn('class="status ${esc(statusClass)}"', js)
        self.assertIn("export function isRuntimeSuspect", js)
        self.assertIn("if(isRuntimeSuspect(a))return'Checking'", js)
        self.assertIn("if(st==='QUEUED')return'queued';if(luaWaiting", js)
        self.assertIn("if(apiLabel==='Queued'||st==='QUEUED')return'Queued';if(luaWaiting", js)
        self.assertIn("return apiLabel}if(isRuntimeSuspect(a))return'Checking'", js)
        self.assertNotIn("if(isRuntimeSuspect(a))return'Checking';if(['Idle','Queued'", js)
        self.assertNotIn("if(isRuntimeSuspect(a))return'Suspect'", js)
        self.assertIn("export function renderAccountRows", js)
        self.assertIn("export function createFeedback", js)
        self.assertIn("export function solarIcon", js)
        self.assertIn("export function applySolarStaticIcons", js)
        self.assertIn("export function bindDashboardEvents", js)
        self.assertIn("export function renderSettingsPanel", js)
        self.assertIn("from '../runtime/status.js'", js)
        self.assertIn("from '../runtime/accountStatus.js'", js)
        self.assertIn("from '../components/accountsTable.js'", js)
        self.assertIn("from '../components/feedback.js'", js)
        self.assertIn("from '../components/icons.js", js)
        self.assertIn("from '../events/bindings.js'", js)
        self.assertIn("from '../panels/settingsPanels.js", js)
        self.assertNotIn("setInterval(manualSnapshot,2500)", js)
        self.assertNotIn("<style>", page)
        self.assertNotIn("<span>Cronus Launcher</span>", html)
        self.assertNotIn('<header class="topbar">', html)
        self.assertNotIn('id="stream-state"', html)
        self.assertNotIn('id="sync-btn"', html)
        self.assertNotIn('class="view-head"', html)
        self.assertNotIn('id="view-kicker"', html)
        self.assertNotIn('id="view-title"', html)
        self.assertNotIn('id="view-sub"', html)
        self.assertIn('class="page-head"', html)
        self.assertIn(".page-head", html)
        self.assertIn("panel-body-only", html)
        self.assertIn('class="side-launch"', html)
        self.assertIn('id="nav-accounts-count"', html)
        sidebar_head = html.split('<aside class="sidebar">', 1)[1].split('<nav id="nav"', 1)[0]
        self.assertIn('id="guard-btn"', sidebar_head)
        side_status = html.split('<section class="side-status">', 1)[1].split('</section>', 1)[0]
        for cls in ("metric-online", "metric-queued", "metric-captcha", "status-running"):
            self.assertIn(cls, html)
        self.assertIn('id="h-online"', side_status)
        self.assertIn('id="h-queued"', side_status)
        self.assertIn('id="h-captcha"', side_status)
        self.assertIn('id="h-running-time"', side_status)
        self.assertIn(">CAPTCHA<", side_status)
        self.assertIn("Running: 0s", side_status)
        self.assertNotIn("System Healthy", side_status)
        self.assertNotIn(">State<", side_status)
        self.assertNotIn(">Done<", side_status)
        self.assertNotIn('id="h-ingame"', side_status)
        self.assertNotIn('id="h-running"', side_status)
        self.assertNotIn('class="ops-bar"', html)
        for ops_id in ("ops-machine-state", "ops-machine-detail", "ops-scheduler-state", "ops-scheduler-detail", "ops-recovery-state", "ops-recovery-detail", "ops-truth-state", "ops-truth-detail"):
            self.assertNotIn(f'id="{ops_id}"', html)
        self.assertNotIn("function renderOpsStatus()", html)
        self.assertNotIn("setOpsCard('ops-machine'", html)
        self.assertNotIn("setOpsCard('ops-scheduler'", html)
        self.assertNotIn("setOpsCard('ops-recovery'", html)
        self.assertNotIn("setOpsCard('ops-truth'", html)
        self.assertIn('id="close-all-roblox-btn"', html)
        self.assertIn("Close All Roblox", html)
        self.assertIn('id="reload-cookies-btn"', html)
        self.assertIn("Reload Cookies", html)
        self.assertNotIn('class="account-stats"', html)
        self.assertNotIn('id="accounts-stat-online"', html)
        self.assertNotIn('id="accounts-stat-queued"', html)
        self.assertNotIn('id="accounts-stat-ingame"', html)
        self.assertNotIn('id="accounts-stat-attention"', html)
        self.assertNotIn(".ops-bar", compact_css)
        self.assertNotIn(".ops-item", compact_css)
        assert_css_contains('@font-face{font-family:"Kanit";src:url("/ui/fonts/Kanit-Regular.ttf") format("truetype");font-weight:400;font-style:normal;font-display:swap}')
        assert_css_contains('@font-face{font-family:"Kanit";src:url("/ui/fonts/Kanit-Medium.ttf") format("truetype");font-weight:500 900;font-style:normal;font-display:swap}')
        assert_css_contains('--font:"Kanit","Segoe UI",system-ui,sans-serif')
        assert_css_contains('--mono:"Kanit","Segoe UI",system-ui,sans-serif')
        assert_css_contains("--panel2:#1A1A1A")
        assert_css_contains("--muted:#71717A")
        spacex_css = compact_css
        assert_css_contains("background:#0A0A0A")
        assert_css_contains("background:#111111")
        assert_css_contains(".nav button.active{background:#202020;color:#FFFFFF;box-shadow:inset 2px 0 0 #FFFFFF}")
        assert_css_contains(".side-launch .guard-action{height:32px;border-radius:6px;background:transparent")
        self.assertIn("SOLAR_ICON_SOURCE='Local PNG UI Icons'", html)
        self.assertIn("data-solar-icon=", html)
        self.assertIn("asset-icon", html)
        for icon_file in (
            "list.png",
            "layers.png",
            "bolt.png",
            "settings.png",
            "play.png",
            "stop-circle.png",
            "user-add.png",
            "trash.png",
            "rotate-right.png",
            "interrogation.png",
        ):
            self.assertIn(icon_file, html)
        self.assertIn("applySolarStaticIcons(document);", html)
        self.assertNotIn("solarIcon('exit','guard-icon stop')", html)
        self.assertIn("guard-icon stop", html)
        self.assertIn("solarIcon('stopCircle','guard-icon stop')", html)
        self.assertIn("guard-icon start", html)
        self.assertIn("solarIcon('play','guard-icon start')", html)
        self.assertNotIn('class="guard-icon start-logo"', html)
        self.assertNotIn('src="/ui/cronus-start-icon.png"', sidebar_head)
        self.assertNotIn('class="guard-icon bolt"', html)
        self.assertNotIn('d="M13 2 4 14h7l-1 8 10-13h-7z"', html)
        self.assertNotIn("solarIcon('playCircle','guard-icon bolt')", html)
        self.assertIn("replaceSvg(root,'#nav button[data-view=\"accounts\"] > svg','list','nav-icon')", html)
        self.assertIn("replaceSvg(root,'#nav [data-nav-group=\"launcher\"] .nav-group-icon svg','layers','nav-icon')", html)
        self.assertIn("replaceSvg(root,'#nav [data-nav-group=\"performance\"] .nav-group-icon svg','bolt','nav-icon')", html)
        self.assertIn("replaceSvg(root,'#nav [data-nav-group=\"tool\"] .nav-group-icon svg','settings','nav-icon')", html)
        self.assertIn("'userAdd','btn-icon'", html)
        self.assertIn("'rotateRight','btn-icon'", html)
        self.assertIn("solarIcon('checkSquare','btn-icon')", html)
        self.assertIn("delete:'trash'", html)
        self.assertIn("install:'downloadSquare'", html)
        self.assertIn("noticeBell:'interrogation.png'", html)
        self.assertIn("close:'trash'", html)
        assert_css_contains(".side-launch .guard-action.good{background:#101a2d;border-color:#1c314f;color:#8ec6ff;box-shadow:none}")
        assert_css_contains(".side-launch .guard-action.good:hover:not(:disabled){background:#13233a;border-color:#29486d;color:#d7ebff;box-shadow:none}")
        assert_css_contains(".side-launch .guard-action.danger{background:#1d101a;border-color:#4a2637;color:#ff7d8e;box-shadow:none}")
        assert_css_contains(".side-launch .guard-action.danger:hover:not(:disabled){background:#2a1420;border-color:#713247;color:#ffb0bb;box-shadow:none}")
        assert_css_contains(".side-launch .guard-action .guard-icon.bolt{filter:none}")
        assert_css_contains(".side-launch .guard-action .guard-icon.stop{filter:none}")
        self.assertNotIn("drop-shadow(0 0 5px rgba(98,162,255", compact_css)
        self.assertNotIn("drop-shadow(0 0 5px rgba(224,91,106", compact_css)
        self.assertNotIn('class="guard-icon play"', html)
        self.assertNotIn('d="M10 8.2v7.6l6-3.8-6-3.8z"', html)
        self.assertNotIn('x="7" y="7" width="10" height="10" rx="1.5"', html)
        self.assertIn("--icon-url:url('/ui/icons/${asset}')", html)
        self.assertIn("--icon-url:url('/ui/icons/play.png')", html)
        for stroke_width in ('stroke-width="2.75"', 'stroke-width="2.45"', 'stroke-width="2.65"'):
            self.assertIn(stroke_width, html)
        assert_css_contains(".nav-root,.nav-group-head{font-weight:800!important}")
        assert_css_contains(".nav-root svg,.nav-group-head svg{width:8px;height:8px;flex-basis:8px}")
        assert_css_contains("left:4px")
        assert_css_contains("pointer-events:none")
        assert_css_contains("transform:translateY(-50%)")
        assert_css_contains("#nav .nav-child.active:before{background:#25334d}")
        self.assertNotIn("--branch-curve:url", html)
        assert_css_contains("background:#13264a")
        self.assertNotIn('rect x="4" y="4" width="16" height="16" rx="4"', html)
        self.assertNotIn('d="M4 9.5h16"', html)
        self.assertNotIn('d="M9.5 9.5V20"', html)
        self.assertNotIn('circle cx="7" cy="7" r="2.5"', html)
        self.assertIn('d="M14.7 6.3a4.6 4.6 0 0 0-5.8 5.8L3.8 17.2a2.1 2.1 0 0 0 3 3l5.1-5.1a4.6 4.6 0 0 0 5.8-5.8l-3.2 3.2-3-3 3.2-3.2z"', html)
        self.assertNotIn('d="M20 7h-9"', html)
        for old_theme in ("rgba(34,197,94", "rgba(126,188,255", "#22c55e", "#3b82f6", "#60a5fa", "#16a34a"):
            self.assertNotIn(old_theme, spacex_css)
        self.assertNotIn(".account-stat-card", html)
        assert_css_contains("max-height:calc(100vh - 360px)")
        self.assertNotIn("function animateViewEntry(viewEl)", html)
        self.assertNotIn("main-view-enter", html)
        self.assertNotIn("viewItemRise", html)
        self.assertNotIn(".view.main-view-enter>*", compact_css)
        self.assertNotIn("animation:viewItemRise.64s", compact_css)
        self.assertNotIn(".view.main-view-enter>:nth-child(2)", compact_css)
        self.assertNotIn("animation-delay:.06s", compact_css)
        self.assertIn("function renderTop(){const c=counts()", html)
        self.assertIn("$('h-captcha').textContent=c.captcha", html)
        self.assertIn("const CONDITIONAL_ACCOUNT_FILTERS=['invalid','captcha']", html)
        self.assertNotIn('data-action="focus-captcha"', html)
        self.assertNotIn('data-action="open-captcha-login"', html)
        self.assertIn('data-action="resume-captcha"', html)
        assert_css_contains(".mini-dot.captcha{background:#e6b450;box-shadow:0 0 10px rgba(230,180,80,.38)}")
        assert_css_contains(".accounts-shell .status.lua{background:rgba(0,255,255,.10);border-color:rgba(0,255,255,.18);color:#00FFFF}")
        assert_css_contains(".accounts-shell .status.lua:before{background:#00FFFF;box-shadow:0 0 8px rgba(0,255,255,.38)}")
        assert_css_contains(".accounts-shell .status.cooldown,.accounts-shell .status.recovery,.accounts-shell .status.network,.accounts-shell .status.captcha{background:rgba(230,180,80,.10);border-color:rgba(230,180,80,.12);color:#f3c96f}")
        assert_css_contains(".accounts-shell .status.cooldown:before,.accounts-shell .status.recovery:before,.accounts-shell .status.network:before,.accounts-shell .status.captcha:before{background:#e6b450}")
        self.assertIn("export function isInvalid(a)", html)
        self.assertIn("return'Invalid'", html)
        self.assertIn("function syncToggleLabels()", html)
        self.assertIn("async function loadDeveloperLua(force=false)", html)
        self.assertIn("api('/lua/executor-loader?ts='+Date.now())", html)
        self.assertIn("const source=await loadDeveloperLua(true)", html)
        self.assertNotIn("input.checked?'Enabled':'Disabled'", html)
        self.assertIn("text.hidden=true", html)
        self.assertIn('.toggle-row input[type="checkbox"]', html)
        self.assertNotIn("accounts-stat-attention", html)
        self.assertIn("/accounts/reload", html)
        self.assertIn("function reloadCookies()", html)
        self.assertIn('id="toast" class="toast" style="z-index:80" role="status" aria-live="polite"', html)
        self.assertIn("toast-icon", html)
        self.assertIn("toast-close", html)
        self.assertIn("Close notification", html)
        self.assertIn(".toast:before", html)
        self.assertIn("z-index: 80", css)
        assert_css_contains(".status{border:0;border-radius:0;padding:0;background:transparent;color:#E5E5E5;font-weight:500;gap:7px}")
        assert_css_contains(".status.finished,.status.blocked{background:transparent;border-color:transparent;color:#C88989}")
        assert_css_contains(".status.invalid{background:transparent;border-color:transparent;color:#d68533}")
        assert_css_contains(".accounts-shell .status.invalid{background:rgba(214,133,51,.13);border-color:rgba(214,133,51,.18);color:#d68533}")
        self.assertIn("/roblox/close-all", html)
        self.assertIn("function confirmCloseAllRoblox()", html)
        self.assertIn("cardIcon('close')", html)
        self.assertIn("Close Roblox only", html)
        self.assertIn("Closes every Roblox window, Cronus stays running", html)
        self.assertNotIn("Stop Cronus and close Roblox</strong>", html)
        self.assertNotIn("Stops Cronus, then closes every Roblox window.", html)
        self.assertNotIn("STATUS.running=false", html)
        self.assertNotIn("confirm('Close all Roblox", html)
        for removed in ('id="h-finished"', 'id="h-cpu"', 'id="h-ram"', ">Finished<", ">CPU<"):
            self.assertNotIn(removed, html)
        self.assertIn('data-view="limiter"', html)
        self.assertNotIn('data-view="ram"', html)
        self.assertNotIn('data-view="cpu-limiter"', html)
        self.assertIn("RAM Limiter", html)
        assert_css_contains(".nav-separator,.nav-badge{display:none!important}")
        self.assertNotIn(".nav-separator,.nav-badge,.side-status{display:none!important}", html)
        self.assertIn("function syncRunningClock()", html)
        self.assertIn("$('nav-accounts-count').textContent=c.all", html)
        self.assertNotIn("Cronus Log", html)
        self.assertNotIn('data-view="logs"', html)
        self.assertNotIn('id="view-logs"', html)
        self.assertNotIn('id="logs-clear"', html)
        self.assertNotIn('id="log-summary"', html)
        self.assertNotIn('id="logs-timeline"', html)
        self.assertNotIn('id="logs-inspector"', html)
        self.assertNotIn('id="logs-raw"', html)
        self.assertNotIn("/runtime/events?limit=350", html)
        self.assertNotIn("function clearLogs()", html)
        self.assertNotIn("function confirmClearLogs()", html)
        self.assertNotIn("Clear Cronus log", html)
        self.assertIn("function confirmDeleteAccount(user)", html)
        self.assertIn("Delete Account", html)
        self.assertIn("cardIcon('delete')", html)
        self.assertIn('class="danger-name"', html)
        self.assertIn("Removes this account and cookie", html)
        self.assertNotIn('<span class="blocked-note">${esc(user)}</span>', html)
        self.assertNotIn("blocked?<div", html)
        self.assertNotIn("Invalid Cookie</span>", html)
        self.assertNotIn("confirm('Delete account", html)
        self.assertIn('data-view="troubleshoot"', html)
        self.assertIn('id="view-troubleshoot"', html)
        self.assertIn(">Tool<", html)
        self.assertIn('data-nav-group="tool"', html)
        self.assertNotIn('data-nav-group="settings"', html)
        self.assertNotIn(">Settings<", html)
        self.assertIn('data-view="developer"', html)
        self.assertIn('id="view-developer"', html)
        self.assertIn('id="developer-copy-lua"', html)
        self.assertIn('id="developer-lua-source"', html)
        self.assertIn(">Copy<", html)
        self.assertNotIn("Copy Lua", html)
        self.assertIn("loadDeveloperLua().catch", html)
        self.assertIn("Copying Lua...", html)
        self.assertNotIn("Lua loaded. Press Copy again", html)
        self.assertIn("setTimeout(()=>resolve(false),500)", html)
        self.assertIn("Lua copied to clipboard", html)
        self.assertIn("Lua selected. Press Ctrl+C to copy", html)
        self.assertIn("/lua/executor-loader", html)
        self.assertIn("function copyDeveloperLua()", html)
        self.assertIn("Roblox Install", html)
        self.assertIn("Currently installed:", html)
        self.assertIn("/troubleshoot/roblox-install", html)
        self.assertIn("function robloxInstallConfirm(action)", html)
        self.assertIn("cardIcon('install')", html)
        self.assertIn("Stop Cronus and close Roblox first", html)
        self.assertIn("TROUBLESHOOT.block_msg", html)
        self.assertNotIn("Downgrade", html)
        self.assertNotIn("roblox-version", html)
        self.assertNotIn("previous Windows version", html)
        self.assertNotIn("/troubleshoot/roblox-install/version", html)
        self.assertNotIn("confirm('Uninstall", html)
        self.assertNotIn("confirm('Download latest", html)
        self.assertNotIn("Cronus RT", html)
        self.assertIn('data-view="limiter"', html)
        self.assertIn('id="view-limiter"', html)
        self.assertIn('data-view="graphics"', html)
        self.assertIn('id="view-graphics"', html)
        self.assertNotIn('id="view-ram"', html)
        self.assertIn('data-view="window-size"', html)
        self.assertIn('id="view-window-size"', html)
        self.assertNotIn('id="view-cpu-limiter"', html)
        game_section = html.split('id="view-game"', 1)[1].split('id="view-limiter"', 1)[0]
        limiter_section = html.split('id="view-limiter"', 1)[1].split('id="view-graphics"', 1)[0]
        fps_section = limiter_section
        ram_section = limiter_section
        graphics_section = html.split('id="view-graphics"', 1)[1].split('id="view-window-size"', 1)[0]
        window_section = html.split('id="view-window-size"', 1)[1].split('id="view-queue"', 1)[0]
        cpu_section = limiter_section
        queue_section = html.split('id="view-queue"', 1)[1].split('id="view-troubleshoot"', 1)[0]
        for button_id in (
            "game-save",
            "game-reset",
            "limiter-save",
            "limiter-reset",
            "graphics-save",
            "graphics-reset",
            "window-size-save",
            "window-size-reset",
            "queue-save",
            "queue-reset",
        ):
            self.assertIn(f'id="{button_id}" hidden', html)
        self.assertIn("save.hidden=!isDirty", html)
        self.assertIn("reset.hidden=!isDirty", html)
        assert_css_contains(".savebar .save-action,.btn.good.settings-dirty,.savebar .save-action.settings-dirty{background:transparent;border-color:rgba(255,255,255,.42);color:#FFFFFF;box-shadow:none}")
        self.assertIn(".savebar .reset-action", html)
        self.assertIn(".savebar .save-action.settings-dirty", html)
        self.assertIn('id="ram-enabled"', ram_section)
        self.assertIn('id="ram-limit-preset"', ram_section)
        self.assertIn('<option value="8192">8 GB</option>', ram_section)
        self.assertIn('<option value="16384">16 GB</option>', ram_section)
        self.assertIn('<option value="32768">32 GB</option>', ram_section)
        self.assertIn('id="ram-limit-custom"', ram_section)
        self.assertIn("roblox_memory_guard_mb:readRamLimit($)", html)
        self.assertIn("toast('RAM Limiter saved')", html)
        assert_css_contains(".limiter-section{display:grid;gap:14px;padding:22px;border-bottom:0}")
        self.assertNotIn(".limiter-section:last-child", css)
        assert_css_contains(".toggle-row span{display:none")
        self.assertEqual(html.count('class="btn ghost reset-action"'), 5)
        self.assertEqual(html.count('class="btn good save-action"'), 5)
        self.assertEqual(html.count('class="btn-icon" aria-hidden="true"'), 13)
        self.assertIn('id="close-all-roblox-btn"><svg class="btn-icon"', html)
        self.assertIn('id="reload-cookies-btn"><svg class="btn-icon"', html)
        self.assertIn('id="add-btn"><svg class="btn-icon"', html)
        self.assertIn("['Idle','Queued','Launching','In Game','Disconnected','Rejoining','Cooldown','Failed'].includes(apiLabel)", html)
        self.assertNotIn("Checking Disconnect", html)
        self.assertNotIn("save.disabled=!isDirty", html)
        self.assertNotIn("reset.disabled=!isDirty", html)
        self.assertIn("function resetGameSettings()", html)
        self.assertIn("function resetQueueSettings()", html)
        self.assertIn("function resetLimiterSettings()", html)
        self.assertIn("async function saveLimiter()", html)
        self.assertIn("function resetPerformanceSettings()", html)
        self.assertIn("function resetGraphicsSettings()", html)
        self.assertIn("function resetWindowSizeSettings()", html)
        self.assertIn("$('game-reset').onclick=a.resetGameSettings", html)
        self.assertIn("$('limiter-reset').onclick=a.resetLimiterSettings", html)
        self.assertIn("$('limiter-save').onclick=a.saveLimiter", html)
        self.assertIn("$('queue-reset').onclick=a.resetQueueSettings", html)
        self.assertNotIn("$('game-reset').onclick=async()=>{clearDirty('game');await loadConfig()}", html)
        self.assertNotIn("$('queue-reset').onclick=async()=>{clearDirty('queue');await loadConfig()}", html)
        self.assertNotIn("Auto Minimize", game_section)
        self.assertNotIn("game-autominimize", html)
        self.assertNotIn("Game Settings", game_section)
        self.assertNotIn("Global defaults for accounts without a target.", game_section)
        self.assertIn('placeholder="Search"', html)
        self.assertIn("Enter Place ID", game_section)
        self.assertIn("Place to join", game_section)
        self.assertIn("Default VIP link", game_section)
        self.assertIn("Free VIP before launch", game_section)
        self.assertNotIn("Close Roblox on timer.", game_section)
        self.assertNotIn("Auto Close", game_section)
        self.assertIn("Auto Reload Roblox (Minute)", queue_section)
        self.assertIn('id="queue-autoclose-enabled"', queue_section)
        self.assertIn('id="queue-autoclose-minutes"', queue_section)
        self.assertNotIn("game-autoclose", html)
        self.assertIn("auto_close_enabled:$('queue-autoclose-enabled').checked", html)
        self.assertIn("Keep other accounts open", game_section)
        for old_copy in (
            "Search accounts...",
            "Enter a Place ID and click Lookup.",
            "Roblox Place ID to join.",
            "Used as the default VIP server for new or blank-target accounts.",
            "Free only / before launch. New VIP servers are named with the Roblox game name.",
            "Close Roblox clients on a timer, then let Cronus Launcher start the queue again.",
            "Keep other account instances alive; Cronus Launcher still closes the duplicate instance for the same account tracker.",
        ):
            self.assertNotIn(old_copy, html)
        self.assertNotIn("Graphics Auto", fps_section)
        self.assertNotIn("Auto Process Priority", fps_section)
        self.assertNotIn("Priority Applied", fps_section)
        self.assertNotIn("Cap Roblox FPS to reduce CPU and GPU usage.", fps_section)
        self.assertIn("FPS Limiter", fps_section)
        self.assertIn("Reduce CPU/GPU usage.", fps_section)
        self.assertNotIn("Limit Roblox FPS.", fps_section)
        self.assertNotIn("15-1000 FPS.", fps_section)
        self.assertNotIn("Limit the framerate of all Roblox instances.", fps_section)
        self.assertNotIn("Frames per second per instance. Allowed range: 15-1000.", fps_section)
        self.assertIn('id="limiter-reset"', fps_section)
        self.assertNotIn('id="fps-reset"', fps_section)
        self.assertNotIn('id="ram-reset"', ram_section)
        self.assertNotIn('id="cpu-reset"', cpu_section)
        self.assertIn("Save Changes", fps_section)
        self.assertIn("Graphics Quality", graphics_section)
        self.assertNotIn("Low Graphics Quality", graphics_section)
        self.assertIn("Auto Process Priority", graphics_section)
        self.assertNotIn("Priority Applied", graphics_section)
        self.assertNotIn("Force Roblox into manual low-quality graphics.", graphics_section)
        self.assertIn("Set Roblox graphics quality", graphics_section)
        self.assertNotIn("Use low Roblox graphics.", graphics_section)
        self.assertNotIn("1 low, 10 high.", graphics_section)
        self.assertIn("Set Roblox process priority", graphics_section)
        self.assertNotIn("Set Roblox to manual low graphics and keep the settings file locked while enabled.", graphics_section)
        self.assertNotIn("1 is lowest, 10 is highest. Use 1 for potato mode.", graphics_section)
        self.assertNotIn("Apply Windows process priority to live Roblox clients and keep reapplying during RT maintenance.", graphics_section)
        self.assertIn('id="graphics-reset"', graphics_section)
        self.assertIn("Window Size", window_section)
        self.assertNotIn("Enable Window Size", window_section)
        self.assertIn('id="window-size-controls" hidden', window_section)
        self.assertIn('id="window-size-custom" class="control-line" hidden', window_section)
        self.assertNotIn("Resize Roblox windows smaller to reduce render load.", window_section)
        self.assertIn("Resize Roblox windows", window_section)
        self.assertIn("Choose window size", window_section)
        self.assertIn("Auto Arrange", window_section)
        self.assertIn("Windows per row", window_section)
        self.assertIn('id="window-arrange-controls" hidden', window_section)
        self.assertNotIn("Minimize Roblox on timer.", window_section)
        self.assertNotIn("Resize live Roblox windows and keep new RT launches at the selected size.", window_section)
        self.assertNotIn("Choose a preset from very small up to 1920 x 1080.", window_section)
        self.assertNotIn("Minimize Roblox windows on a loop.", window_section)
        self.assertIn('id="window-size-reset"', window_section)
        self.assertNotIn("Auto Minimize", window_section)
        self.assertNotIn('id="window-autominimize-enabled"', window_section)
        self.assertNotIn('id="window-autominimize-controls" class="control-line" hidden', window_section)
        self.assertIn("320 x 240", window_section)
        self.assertIn("1920 x 1080", window_section)
        self.assertIn("function saveWindowSize()", html)
        self.assertIn("/performance/window-size", html)
        self.assertIn("CPU Limiter", cpu_section)
        self.assertIn("Limit Roblox CPU usage.", cpu_section)
        self.assertNotIn("Enable CPU Limiter", cpu_section)
        self.assertIn("Default CPU Limit", cpu_section)
        self.assertIn("Apply to all accounts", cpu_section)
        self.assertIn("Roblox PID", cpu_section)
        self.assertIn("Limit %", cpu_section)
        self.assertIn('id="cpu-controls" hidden', cpu_section)
        self.assertIn("function saveCpuLimiter()", html)
        self.assertIn("/performance/cpu-limiter", html)
        self.assertIn("LIMITER_VIEWS=['performance','ram','cpu-limiter']", html)
        self.assertIn("updateLimiterSaveState()", html)
        assert_css_contains("grid-template-columns:minmax(180px,250px) minmax(220px,320px)")
        assert_css_contains("#fps-limit-field,#ram-current-field,#window-size-controls,#window-arrange-controls,#graphics-quality-controls,#autoclose-controls,#priority-controls,#cpu-controls{display:grid;gap:10px}")
        for label in ("Settings File", "Current File Cap", "Read-only", "Roblox State"):
            self.assertNotIn(label, fps_section)
            self.assertNotIn(label, graphics_section)
        self.assertNotIn("AccountData Import", html)
        self.assertIn("choice-icon", html)
        self.assertIn("function openAdd(){openCookie()}", html)
        self.assertNotIn("function openManualMode()", html)
        self.assertNotIn('id="manual-single"', html)
        self.assertNotIn('id="manual-multi"', html)
        self.assertNotIn("function openManualSingle()", html)
        self.assertNotIn("function openManualMulti()", html)
        self.assertNotIn("Manual Login", html)
        self.assertNotIn("Login in browser.", html)
        self.assertIn("Import Cookies", html)
        self.assertIn("One cookie per line", html)
        self.assertNotIn("One login.", html)
        self.assertNotIn("One account per line.", html)
        self.assertNotIn("manual-login", html)
        self.assertNotIn("kind:'userpass'", html)
        self.assertIn("Save changes first", html)
        for old_copy in (
            "Sign in via a popup browser. 2FA, captcha, and passkey stay with you.",
            "Paste user:pass:cookie or cookie-only lines.",
            "One account. Enter optional credentials, sign in once.",
            "Paste user:pass per line. Popups open one after another.",
            "Save Changes before running or launching",
            "This removes the account record and its stored cookie",
        ):
            self.assertNotIn(old_copy, html)
        self.assertIn('class="avatar-img"', html)
        self.assertNotIn('id="window-autominimize-enabled"', html)
        self.assertIn('id="game-auto-private-enabled"', html)
        self.assertNotIn("Name Template", html)
        self.assertNotIn('id="auto-private-controls"', html)
        self.assertNotIn('id="game-private-name-template"', html)
        self.assertIn("auto_create_private_server_enabled", html)
        self.assertNotIn('id="window-autominimize-controls" class="control-line" hidden', html)
        self.assertNotIn('class="compact-toggle-row"', html)
        self.assertNotIn('id="fps-inline-label">Disabled</span>', html)
        self.assertIn('id="fps-limit-field" hidden', html)
        self.assertIn('id="priority-controls" hidden', html)
        self.assertNotIn('id="graphics-quality-label">Disabled</span>', html)
        self.assertIn('id="graphics-quality-controls" hidden', html)
        self.assertNotIn('id="autoclose-inline-label">Disabled</span>', html)
        self.assertIn('id="autoclose-controls" hidden', html)
        self.assertNotIn("setCompactToggle(", html)
        self.assertNotIn('id="presence-controls"', html)
        self.assertNotIn('id="presence-interval"', html)
        self.assertNotIn('id="presence-ttl"', html)
        self.assertNotIn('id="presence-assist"', html)
        self.assertNotIn('id="presence-last-poll"', html)
        self.assertNotIn('id="presence-cached"', html)
        self.assertNotIn('id="presence-backoff"', html)
        self.assertNotIn('id="presence-status"', html)
        for new_copy in (
            "Max active accounts",
            "Used only for rotation",
            "Delay between launches",
            "Detect Roblox disconnect popup",
        ):
            self.assertIn(new_copy, queue_section)
        for old_copy in (
            "Maximum accounts allowed in queued, launching, verifying, or in-game slots.",
            "Ignored while Multi Roblox keep-all-open is enabled; rotation must be enabled separately.",
            "Wait time between launches and between cycling an account back into the queue.",
            "Use Roblox presence as extra evidence before rejoin decisions.",
            "Seconds between Roblox presence checks.",
            "Seconds to reuse presence results.",
        ):
            self.assertNotIn(old_copy, queue_section)
        self.assertIn(".main::-webkit-scrollbar", html)
        self.assertIn(".table-wrap::-webkit-scrollbar", html)
        title_source = inspect.getsource(main._run_desktop_window)
        self.assertIn("MacCloseButton", title_source)
        self.assertIn("MacMinButton", title_source)
        self.assertIn("MacMaxButton", title_source)
        self.assertIn("_title_icon_pixmap", title_source)
        self.assertIn('TITLE_ICON_FILE = resource_path("assets", APP_ICON_FILE)', title_source)
        self.assertIn("QFontDatabase", title_source)
        self.assertIn('resource_path("ui", "fonts", "Kanit-Regular.ttf")', title_source)
        self.assertIn('resource_path("ui", "fonts", "Kanit-Medium.ttf")', title_source)
        self.assertIn("QFontDatabase.addApplicationFont(font_file)", title_source)
        self.assertIn("_load_title_fonts()", title_source)
        self.assertIn('font-family: "Kanit";', title_source)
        self.assertIn("font-weight: 500;", title_source)
        self.assertIn("QSize", title_source)
        self.assertIn("QPen", title_source)
        self.assertIn("def _window_control_icon(kind: str) -> QIcon:", title_source)
        self.assertIn('painter.drawLine(5, 8, 11, 8)', title_source)
        self.assertIn("painter.drawRect(5, 5, 6, 6)", title_source)
        self.assertIn("self._status_icon.setFixedSize(22, 22)", title_source)
        self.assertIn("self._status_icon.setAlignment(Qt.AlignmentFlag.AlignCenter)", title_source)
        self.assertIn("layout.setSpacing(6)", title_source)
        self.assertIn("width: 34px; height: 22px; min-width: 34px; max-width: 34px;", title_source)
        self.assertIn("padding: 0px;", title_source)
        self.assertIn("button.setFixedSize(34, 22)", title_source)
        self.assertIn("button.setIcon(_window_control_icon(icon_name))", title_source)
        self.assertIn("button.setIconSize(QSize(16, 16))", title_source)
        self.assertIn('self._button("WinMinButton", "Minimize", "minimize")', title_source)
        self.assertIn('self._button("WinMaxButton", "Maximize", "maximize")', title_source)
        self.assertIn('self._button("WinCloseButton", "Close", "close")', title_source)
        self.assertNotIn("_tinted_title_icon", title_source)
        self.assertNotIn("TitleButton", title_source)
