const lower=s=>String(s||'').toLowerCase();
const num=v=>Number(v||0)||0;

function truthState(a){return lower(a?.runtime_truth?.truth_state)}
function truthReasons(a){return Array.isArray(a?.runtime_truth?.reasons)?a.runtime_truth.reasons.join(' '):''}
function statusText(a){return lower([a?.recovery_status,a?.last_recovery_reason,a?.last_state_reason,a?.last_crash_reason,a?.watchdog_classification,a?.health_flags,a?.recovery_step,a?.blocked_reason,a?.manual_status,a?.last_error,truthState(a),truthReasons(a)].filter(Boolean).join(' '))}
export function isRuntimeSuspect(a){return truthState(a)==='suspect'}

export function isCaptcha(a){
  const text=statusText(a);
  return !!a?.captcha_required||text.includes('captcha')||text.includes('arkose')||text.includes('funcaptcha')||text.includes('challenge required')||text.includes('security challenge');
}

export function isInvalid(a){const reason=lower([a?.blocked_reason,a?.manual_status,a?.import_status,a?.last_recovery_reason,a?.last_state_reason].filter(Boolean).join(' '));return !isCaptcha(a)&&(reason.includes('cookie_invalid')||(reason.includes('cookie')&&(reason.includes('invalid')||reason.includes('expired')||reason.includes('authenticated')||reason.includes('validation failed')||reason.includes('missing'))))}

export function isBlocked(a){return !isCaptcha(a)&&!isInvalid(a)&&(a.launchable===false||!!a.blocked_reason||!!a.cookie_mismatch)}

export function blockedStatusLabel(a){const reason=lower(a?.blocked_reason||a?.manual_status||a?.import_status||a?.last_recovery_reason||a?.last_state_reason||'');if(isCaptcha(a))return'Captcha';if(isInvalid(a))return'Invalid';if(reason.includes('multi_roblox_guard_failed')||reason.includes('multi roblox guard'))return'Guard Failed';if(reason.includes('cookie_mismatch')||reason.includes('cookie mismatch')||reason.includes('cookie belongs'))return'Cookie Mismatch';return'Blocked'}

export function isNetworkIssue(a){const st=String(a?.public_state||a?.state||'').toUpperCase(),rs=String(a?.runtime_state||'').toUpperCase(),live=lower(a?.liveness_state),text=statusText(a),active=['NETWORK_LOST','COOLDOWN','RECOVERING'].includes(st)||['RECOVERING','BACKOFF'].includes(rs),popupText=text.includes('disconnect_dialog')||text.includes('visual_disconnect')||text.includes('session_conflict')||text.includes('error 273')||text.includes('code 273'),netText=popupText||text.includes('network_lost')||text.includes('network lost')||text.includes('network_drop')||text.includes('network drop')||text.includes('connection_error')||text.includes('connection error')||text.includes('disconnected')||text.includes('disconnect')||text.includes('error 277')||text.includes('code 277');return st==='NETWORK_LOST'||live==='reconnecting'||popupText||(active&&netText)}

function luaWaiting(a){return !!a?.lua_required&&!a?.lua_online}

export function isStableInGame(a){const st=String(a?.public_state||a?.state||'').toUpperCase(),rs=String(a?.runtime_state||'').toUpperCase(),cmd=lower(a?.command_inflight?.action||a?.command_inflight||'');return !luaWaiting(a)&&!!a?.pid&&a?.process_alive!==false&&!isRuntimeSuspect(a)&&(st==='IN_GAME'||rs==='RUNNING')&&!cmd&&!['NETWORK_LOST','COOLDOWN','FAILED','CRASH'].includes(st)}

export function bucket(a){if(isCaptcha(a))return'captcha';if(isInvalid(a))return'invalid';if(isBlocked(a))return'blocked';const st=String(a.public_state||a.state||'').toUpperCase(),rs=String(a.runtime_state||'').toUpperCase();if(luaWaiting(a)&&(a.pid||st==='IN_GAME'||rs==='RUNNING'))return'queued';if(isStableInGame(a))return'online';if(isRuntimeSuspect(a))return'recovery';if(isNetworkIssue(a))return'network';if(!luaWaiting(a)&&(st==='IN_GAME'||rs==='RUNNING'&&a.pid))return'online';if(st==='QUEUED')return'queued';if(st==='IDLE'||st==='READY'||rs==='STOPPED')return'idled';if(st==='COOLDOWN')return'cooldown';if(st==='FAILED'||st==='CRASH')return'finished';if(['LAUNCHING','VERIFY','NETWORK_LOST'].includes(st)||lower(a.recovery_status).includes('recover'))return'recovery';return'queued'}

export function label(b){return{all:'All',online:'Online',queued:'Queued',invalid:'Invalid',captcha:'Captcha',idled:'Idled',finished:'Finished',blocked:'Blocked',banned:'Banned',locked:'Locked',recovery:'Recovery',cooldown:'Cooldown',network:'Disconnected'}[b]||'Queued'}

export function counts(accounts){const out={all:accounts.length,online:0,queued:0,invalid:0,captcha:0,idled:0,finished:0,blocked:0,banned:0,locked:0,recovery:0,cooldown:0,network:0};accounts.forEach(a=>out[bucket(a)]++);return out}

export function filterAccounts(accounts,query,cfgFor){const q=lower(query||'');return accounts.filter(a=>{if(!q)return true;const cfg=cfgFor(a.username);return lower([a.username,a.display,cfg.alias,a.description,cfg.description,a.state,a.pid].join(' ')).includes(q)})}

export function rowStatusLabel(a,b){if(isCaptcha(a))return'Captcha';if(isInvalid(a))return'Invalid';if(isBlocked(a))return blockedStatusLabel(a);const st=String(a.public_state||a.state||'').toUpperCase(),rs=String(a.runtime_state||'').toUpperCase(),cmd=lower(a.command_inflight?.action||a.command_inflight||''),text=statusText(a),apiLabel=String(a.state_label||'').trim();if(apiLabel==='Captcha')return'Captcha';if(luaWaiting(a)&&(apiLabel==='Waiting For Lua'||a.pid||st==='IN_GAME'||rs==='RUNNING'))return'Waiting For Lua';if(isStableInGame(a))return'Online';if(isRuntimeSuspect(a))return'Suspect';if(['Idle','Queued','Launching','In Game','Disconnected','Rejoining','Cooldown','Failed'].includes(apiLabel)){if(apiLabel==='In Game')return'Online';if(apiLabel==='Idle')return'Idled';if(apiLabel==='Failed')return'Finished';return apiLabel}if(cmd.includes('launch'))return'Launching';if(cmd.includes('rejoin'))return'Rejoining';if(text.includes('rejoin')||text.includes('recover')||text.includes('session_conflict')||text.includes('error 273')||text.includes('code 273')||text.includes('security_kick')||text.includes('unexpected_client_behavior'))return'Rejoining';if(text.includes('connection_error')||text.includes('visual_disconnect')||text.includes('disconnect_dialog')||text.includes('disconnected')||text.includes('disconnect')||text.includes('error 277')||text.includes('code 277'))return'Disconnected';if(isNetworkIssue(a))return'Disconnected';if(st==='QUEUED')return'Queued';if(st==='LAUNCHING'||rs==='STARTING')return'Launching';if(st==='VERIFY'||rs==='JOINING')return'Rejoining';if(!luaWaiting(a)&&(st==='IN_GAME'||rs==='RUNNING'&&a.pid))return'Online';if(st==='COOLDOWN'||rs==='BACKOFF')return'Cooldown';if(st==='FAILED'||st==='CRASH')return'Finished';if(['IDLE','READY'].includes(st)||rs==='STOPPED')return'Idled';if(st==='RECOVERING'||rs==='RECOVERING')return'Rejoining';return label(b)}

export function rowStatusTitle(a,b){const parts=[rowStatusLabel(a,b)],detail=[a.public_state||a.state||'',a.runtime_state||'',a.recovery_status||'',a.last_recovery_reason||a.last_state_reason||a.last_crash_reason||'',a.liveness_state||''].filter(Boolean).join(' / ');if(detail)parts.push(detail);if(a?.runtime_truth?.truth_state)parts.push(`truth ${a.runtime_truth.truth_state} ${num(a.runtime_truth.confidence)}%`);if(truthReasons(a))parts.push(truthReasons(a));if(a.blocked_reason)parts.push(a.blocked_reason);if(num(a.cooldown_left)>0)parts.push('cooldown '+num(a.cooldown_left)+'s');if(a.pid)parts.push('PID '+a.pid);return parts.join(' - ')}
