from __future__ import annotations

"""
Auto-update for the packaged Cronus Launcher exe.

How it works
------------
1. Every packaged build embeds the upstream commit SHA it was built from
   (see build_info.py, generated by ops/build_exe.py).
2. At startup the app queries GitHub for the current `main` commit and for
   published releases. A release is built automatically by the GitHub Actions
   workflow in .github/workflows/build-release.yml and tagged `build-<sha>`
   with the exe attached as `CronusLauncher.exe`.
3. If the newest release built from the current `main` commit differs from the
   running build, the new exe is downloaded next to the running exe as
   `<exe>.new`. A small `update_apply.cmd` is spawned (hidden) that waits for
   this process to exit, replaces the exe and relaunches it. Nothing is
   replaced while the app is running.

The update is always applied on exit, never mid-session, so the farm is not
interrupted. The dashboard shows a banner with an "Update & restart" action.

Control
-------
- CRONUS_UPDATE_MODE=auto   (default) check + download + apply on exit
- CRONUS_UPDATE_MODE=notify only report, never download
- CRONUS_UPDATE_MODE=off    disable entirely
- CRONUS_UPDATE_REPO=owner/repo  override the upstream repository
"""

import json
import os
import subprocess
import threading
import time
import urllib.error
import urllib.request
from typing import Any, Dict, Optional

from app_paths import BUNDLE_DIR, EXECUTABLE_PATH, IS_COMPILED
from core import flog, flog_kv

try:  # build_info.py is generated by ops/build_exe.py; missing in source runs
    import build_info
except Exception:  # pragma: no cover - only when running from a source checkout
    build_info = None  # type: ignore[assignment]

GITHUB_REPO = str(os.environ.get("CRONUS_UPDATE_REPO", "your-github-username/Roblox-Auto-Rejoin-windows")).strip("/")
API_BASE = "https://api.github.com"
REPO_API = f"{API_BASE}/repos/{GITHUB_REPO}"
ASSET_NAME = "CronusLauncher.exe"
USER_AGENT = "CronusLauncherUpdater/1.0"
_HTTP_TIMEOUT = 12.0

_LOCK = threading.RLock()
_STATE: Dict[str, Any] = {
    "enabled": False,
    "mode": "off",
    "build_commit": "unknown",
    "build_commit_short": "unknown",
    "build_date": "",
    "checked_at": 0,
    "checking": False,
    "last_error": "",
    "remote_commit": "",
    "remote_commit_date": "",
    "release_tag": "",
    "release_commit": "",
    "release_url": "",
    "asset_url": "",
    "asset_size": 0,
    "asset_updated_at": "",
    "update_available": False,
    "status": "disabled",
    "downloading": False,
    "download_pending": False,
    "download_path": "",
    "downloaded_at": 0,
    "apply_spawned": False,
    "restarting": False,
}
_CHECKER_STARTED = False
_APPLY_CMD_SPAWNED = False


def _mode() -> str:
    value = os.environ.get("CRONUS_UPDATE_MODE", "auto").strip().lower()
    if value not in ("auto", "notify", "off"):
        return "auto"
    return value


def _build_commit() -> str:
    try:
        return str(getattr(build_info, "BUILD_COMMIT", "") or "").strip() or "unknown"
    except Exception:
        return "unknown"


def _build_commit_short() -> str:
    commit = _build_commit()
    return commit[:7] if commit and commit != "unknown" else "unknown"


def _build_date() -> str:
    try:
        return str(getattr(build_info, "BUILD_DATE", "") or "").strip()
    except Exception:
        return ""


def _http_json(url: str, timeout: float = _HTTP_TIMEOUT) -> Any:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT, "Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8", errors="replace"))


def _exe_name() -> str:
    return os.path.basename(EXECUTABLE_PATH) if IS_COMPILED else "CronusLauncher.exe"


def _update_cmd_path() -> str:
    return os.path.join(BUNDLE_DIR, "update_apply.cmd")


def _new_exe_path() -> str:
    return os.path.join(BUNDLE_DIR, f"{_exe_name()}.new")


def status() -> Dict[str, Any]:
    with _LOCK:
        return dict(_STATE)


def _set(**fields: Any) -> None:
    with _LOCK:
        _STATE.update(fields)


def _fetch_latest_commit() -> Dict[str, str]:
    """Return {'sha': ..., 'date': ...} for the upstream default branch."""
    data = _http_json(f"{REPO_API}/commits/main")
    if not isinstance(data, dict):
        raise RuntimeError("unexpected commits response")
    sha = str(data.get("sha") or "").strip()
    if not sha:
        raise RuntimeError("empty commit sha")
    date = ""
    try:
        date = str(data.get("commit", {}).get("committer", {}).get("date") or "").strip()
    except Exception:
        pass
    return {"sha": sha, "date": date}


def _fetch_releases() -> list:
    data = _http_json(f"{REPO_API}/releases?per_page=20")
    if not isinstance(data, list):
        raise RuntimeError("unexpected releases response")
    return data


def _release_sha(tag: str) -> str:
    tag = str(tag or "").strip()
    if tag.startswith("build-"):
        return tag[len("build-"):].strip()
    return ""


def _asset_of(release: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    for asset in release.get("assets") or []:
        if str(asset.get("name") or "") == ASSET_NAME:
            return asset
    return None


def _pick_update_release(releases: list, remote_sha: str, build_commit: str) -> Optional[Dict[str, Any]]:
    """Newest release (by published_at) that carries the exe asset for `remote_sha`.

    Returns the release dict when it is newer than the running build, else None.
    """
    candidates: list = []
    for release in releases or []:
        if release.get("draft"):
            continue
        asset = _asset_of(release)
        if not asset:
            continue
        sha = _release_sha(str(release.get("tag_name") or ""))
        if not sha or sha != remote_sha:
            continue
        candidates.append(release)
    if not candidates:
        return None
    candidates.sort(key=lambda r: str(r.get("published_at") or ""), reverse=True)
    chosen = candidates[0]
    chosen_sha = _release_sha(str(chosen.get("tag_name") or ""))
    if chosen_sha == build_commit:
        return None  # already running the newest packaged build
    return chosen


def check_for_update(*, force: bool = False) -> Dict[str, Any]:
    """Query GitHub and refresh _STATE. Never raises; errors land in state."""
    with _LOCK:
        if _STATE["checking"] and not force:
            return dict(_STATE)
        _STATE["checking"] = True
    mode = _mode()
    enabled = bool(IS_COMPILED and mode != "off")
    try:
        if not enabled:
            _set(
                enabled=False,
                mode=mode,
                build_commit=_build_commit(),
                build_commit_short=_build_commit_short(),
                build_date=_build_date(),
                checked_at=time.time(),
                checking=False,
                status="disabled",
                update_available=False,
                last_error="",
            )
            if mode != "off":
                flog("[UPDATE] Skipped: updates are only available in the packaged exe")
            return status()

        commit = _fetch_latest_commit()
        releases = _fetch_releases()
        remote_sha = commit["sha"]
        target = _pick_update_release(releases, remote_sha, _build_commit())

        base = {
            "enabled": True,
            "mode": mode,
            "build_commit": _build_commit(),
            "build_commit_short": _build_commit_short(),
            "build_date": _build_date(),
            "checked_at": time.time(),
            "checking": False,
            "last_error": "",
            "remote_commit": remote_sha,
            "remote_commit_date": commit["date"],
            "update_available": False,
            "download_pending": bool(_STATE.get("download_pending")),
            "downloading": bool(_STATE.get("downloading")),
            "download_path": str(_STATE.get("download_path") or ""),
            "downloaded_at": float(_STATE.get("downloaded_at") or 0),
        }

        if target is None:
            latest_release = next((r for r in releases if not r.get("draft")), None)
            latest_sha = _release_sha(str((latest_release or {}).get("tag_name") or ""))
            if latest_sha == remote_sha:
                base["status"] = "up_to_date"
                base["release_tag"] = str((latest_release or {}).get("tag_name") or "")
                base["release_commit"] = latest_sha
                flog(f"[UPDATE] Up to date (build-{_build_commit_short()}, main {remote_sha[:7]})")
            elif latest_sha == _build_commit():
                base["status"] = "up_to_date"
                base["release_tag"] = str((latest_release or {}).get("tag_name") or "")
                base["release_commit"] = latest_sha
                flog(f"[UPDATE] Up to date (build-{_build_commit_short()})")
            else:
                base["status"] = "release_pending"
                base["release_tag"] = str((latest_release or {}).get("tag_name") or "")
                base["release_commit"] = latest_sha
                flog(
                    f"[UPDATE] Source is ahead of the packaged release "
                    f"(main {remote_sha[:7]}, latest packaged {latest_sha[:7] or 'none'}). "
                    f"An exe will be published automatically when the next release builds."
                )
            _set(**base)
            return status()

        asset = _asset_of(target)
        base.update(
            {
                "status": "update_available",
                "update_available": True,
                "release_tag": str(target.get("tag_name") or ""),
                "release_commit": _release_sha(str(target.get("tag_name") or "")),
                "release_url": str(target.get("html_url") or ""),
                "asset_url": str(asset.get("browser_download_url") or "") if asset else "",
                "asset_size": int(asset.get("size") or 0) if asset else 0,
                "asset_updated_at": str(asset.get("updated_at") or "") if asset else "",
            }
        )
        flog(
            f"[UPDATE] New version available: build-{base['release_commit'][:7]} "
            f"(running build-{_build_commit_short()}). Downloading..."
        )
        _set(**base)
        return status()
    except urllib.error.HTTPError as exc:
        _set(checking=False, last_error=f"GitHub HTTP {exc.code}", status="error")
        flog_kv("UPDATE", "check_http_error", "warning", code=exc.code, error=str(exc))
    except Exception as exc:
        _set(checking=False, last_error=f"{type(exc).__name__}: {exc}", status="error")
        flog_kv("UPDATE", "check_failed", "warning", error=str(exc))
    return status()


def download_update() -> Dict[str, Any]:
    """Download the pending update exe next to the running exe as <exe>.new."""
    if not IS_COMPILED:
        _set(status="disabled", last_error="source mode")
        return status()
    with _LOCK:
        if _STATE.get("downloading"):
            return dict(_STATE)
        if not _STATE.get("asset_url"):
            _set(status="error", last_error="no asset url; run check first")
            return dict(_STATE)
        if _STATE.get("download_pending"):
            return dict(_STATE)
        _STATE["downloading"] = True
    url = str(_STATE.get("asset_url") or "")
    target = _new_exe_path()
    try:
        os.makedirs(BUNDLE_DIR, exist_ok=True)
        flog(f"[UPDATE] Downloading {_exe_name()} from {GITHUB_REPO} ...")
        req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
        with urllib.request.urlopen(req, timeout=300.0) as resp, open(target, "wb") as out:
            total = 0
            while True:
                chunk = resp.read(1024 * 256)
                if not chunk:
                    break
                out.write(chunk)
                total += len(chunk)
        if total < 1_000_000 or not _looks_like_exe(target):
            os.remove(target)
            raise RuntimeError(f"downloaded file is not a valid exe ({total} bytes)")
        expected = int(_STATE.get("asset_size") or 0)
        if expected and abs(total - expected) > 4096:
            flog_kv("UPDATE", "download_size_mismatch", "warning", expected=expected, got=total)
        _set(
            downloading=False,
            download_pending=True,
            download_path=target,
            downloaded_at=time.time(),
            status="downloaded",
            last_error="",
        )
        flog(f"[UPDATE] Update downloaded to {target} - it will apply when Cronus exits.")
        _maybe_spawn_apply_cmd()
        return status()
    except Exception as exc:
        try:
            if os.path.exists(target):
                os.remove(target)
        except Exception:
            pass
        _set(downloading=False, status="error", last_error=f"download failed: {exc}")
        flog_kv("UPDATE", "download_failed", "error", error=str(exc))
        return status()


def _looks_like_exe(path: str) -> bool:
    try:
        with open(path, "rb") as f:
            return f.read(2) == b"MZ"
    except Exception:
        return False


def _spawn_apply_cmd() -> None:
    global _APPLY_CMD_SPAWNED
    if not IS_COMPILED:
        return
    cmd_path = _update_cmd_path()
    exe_name = _exe_name()
    # Note: Windows' find.exe is referenced by absolute path because a Git
    # Bash install on the PATH shadows `find` with GNU find, which does not
    # understand /I and would break the wait loop.
    lines = [
        "@echo off",
        ":waitloop",
        f'tasklist /FI "IMAGENAME eq {exe_name}" 2>NUL | %SystemRoot%\\System32\\find.exe /I "{exe_name}" >NUL',
        "if not errorlevel 1 (",
        "  ping -n 2 127.0.0.1 >NUL",
        "  goto waitloop",
        ")",
        f'move /y "%~dp0{exe_name}.new" "%~dp0{exe_name}" >NUL 2>NUL',
        "if errorlevel 1 (",
        '  echo update-replace-failed > "%~dp0update_failed.txt"',
        "  exit /b 1",
        ")",
        f'start "" "%~dp0{exe_name}"',
        'del "%~f0" >NUL 2>NUL',
        "exit /b 0",
    ]
    try:
        with open(cmd_path, "w", encoding="utf-8", newline="") as f:
            f.write("\r\n".join(lines) + "\r\n")
        subprocess.Popen(
            [cmd_path],
            cwd=BUNDLE_DIR,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
            close_fds=True,
        )
        _APPLY_CMD_SPAWNED = True
        _set(apply_spawned=True)
        flog("[UPDATE] Update helper scheduled - will replace the exe and relaunch on exit.")
    except Exception as exc:
        flog_kv("UPDATE", "apply_cmd_spawn_failed", "error", error=str(exc))


def _maybe_spawn_apply_cmd() -> None:
    global _APPLY_CMD_SPAWNED
    if _APPLY_CMD_SPAWNED:
        return
    if _mode() != "auto":
        return
    if not _STATE.get("download_pending"):
        return
    if not os.path.exists(_new_exe_path()):
        return
    _spawn_apply_cmd()


def apply_update() -> Dict[str, Any]:
    """Ensure the update is downloaded, then schedule replacement on exit."""
    if not IS_COMPILED:
        _set(status="disabled", last_error="source mode")
        return status()
    if not _STATE.get("download_pending"):
        check_for_update(force=True)
        if _STATE.get("update_available"):
            download_update()
    if not _STATE.get("download_pending"):
        return status()
    _maybe_spawn_apply_cmd()
    return status()


def start_update_checker(delay: float = 3.0) -> None:
    """Start the background update check. Safe to call multiple times."""
    global _CHECKER_STARTED
    with _LOCK:
        if _CHECKER_STARTED:
            return
        _CHECKER_STARTED = True

    def _run() -> None:
        try:
            time.sleep(max(0.0, float(delay)))
            check_for_update()
            if _mode() == "auto" and _STATE.get("update_available"):
                download_update()
        except Exception as exc:  # never let a background thread crash the app
            flog_kv("UPDATE", "checker_unexpected", "warning", error=str(exc))

    threading.Thread(target=_run, daemon=True, name="CronusUpdateChecker").start()
