#!/usr/bin/env python3
"""
Build the standalone CronusLauncher.exe with PyInstaller.

The exe bundles Python, PySide6/QtWebEngine, the FastAPI backend, the UI and
the Lua helpers, so target machines need nothing installed - just run the exe.

Usage:
    python ops/build_exe.py [--console] [--name CronusLauncher]

By default the build is windowed (no console window). The upstream commit SHA
is embedded into build_info.py so the built-in auto-updater can compare it
with the latest GitHub release. Resolution order:

    CRONUS_BUILD_COMMIT env var
    git rev-parse HEAD         (when building inside a git clone)
    GitHub API                 (default branch of CRONUS_UPDATE_REPO)
    "unknown"
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import shutil
import subprocess
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GITHUB_REPO = os.environ.get("CRONUS_UPDATE_REPO", "your-github-username/Roblox-Auto-Rejoin-windows").strip("/")


def resolve_commit() -> str:
    override = os.environ.get("CRONUS_BUILD_COMMIT", "").strip()
    if override:
        return override
    try:
        head = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        if head.returncode == 0 and head.stdout.strip():
            return head.stdout.strip()
    except Exception:
        pass
    try:
        req = urllib.request.Request(
            f"https://api.github.com/repos/{GITHUB_REPO}/commits/main",
            headers={"User-Agent": "CronusLauncherBuild/1.0", "Accept": "application/vnd.github+json"},
        )
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        sha = str(data.get("sha") or "").strip()
        if sha:
            return sha
    except Exception:
        pass
    return "unknown"


def commit_date(commit: str) -> str:
    if not commit or commit == "unknown":
        return ""
    try:
        req = urllib.request.Request(
            f"https://api.github.com/repos/{GITHUB_REPO}/commits/{commit}",
            headers={"User-Agent": "CronusLauncherBuild/1.0", "Accept": "application/vnd.github+json"},
        )
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        return str(data.get("commit", {}).get("committer", {}).get("date") or "").strip()
    except Exception:
        return ""


def write_build_info(commit: str, commit_date_value: str) -> None:
    short = commit[:7] if commit and commit != "unknown" else "unknown"
    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    source = "env"
    if commit == "unknown":
        source = "unknown"
    elif os.environ.get("CRONUS_BUILD_COMMIT"):
        source = "env"
    else:
        try:
            head = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                cwd=str(ROOT),
                capture_output=True,
                text=True,
                timeout=10,
                check=False,
            )
            source = "git" if head.returncode == 0 and head.stdout.strip() == commit else "github"
        except Exception:
            source = "github"
    content = f'''from __future__ import annotations

# This file is generated by ops/build_exe.py - do not edit by hand.
# The values identify the upstream source this build was packaged from.

BUILD_COMMIT: str = "{commit}"
BUILD_COMMIT_SHORT: str = "{short}"
BUILD_COMMIT_DATE: str = "{commit_date_value}"
BUILD_DATE: str = "{now}"
BUILD_SOURCE: str = "{source}"


def build_version_label() -> str:
    if BUILD_COMMIT and BUILD_COMMIT != "unknown":
        return f"build-{{BUILD_COMMIT_SHORT}}"
    return "source"
'''
    (ROOT / "build_info.py").write_text(content, encoding="utf-8")
    print(f"[build] wrote build_info.py commit={commit} date={commit_date_value} source={source}")


def make_version_file(build_date: datetime.datetime) -> Path:
    """Write a Windows version resource so the exe carries proper metadata.

    Antivirus heuristics flag files that look anonymous/packed; a correct
    version block (company, product, description) reduces false positives.
    """
    version_dir = ROOT / "build"
    version_dir.mkdir(parents=True, exist_ok=True)
    ver = (
        build_date.year,
        build_date.month,
        build_date.day,
        max(1, min(99, build_date.hour + 1)),
    )
    ver_text = ".".join(str(part) for part in ver)
    content = f"""VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={ver},
    prodvers={ver},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'Cronus'),
         StringStruct('FileDescription', 'Cronus Launcher - Roblox auto rejoin and recovery tool'),
         StringStruct('FileVersion', '{ver_text}'),
         StringStruct('InternalName', 'CronusLauncher'),
         StringStruct('LegalCopyright', 'Copyright (c) {build_date.year} Cronus'),
         StringStruct('OriginalFilename', 'CronusLauncher.exe'),
         StringStruct('ProductName', 'Cronus Launcher'),
         StringStruct('ProductVersion', '{ver_text}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    path = version_dir / "version_info.txt"
    path.write_text(content, encoding="utf-8")
    print(f"[build] wrote version info {ver_text}")
    return path


def make_icon() -> Path:
    icon_png = ROOT / "assets" / "cronus_icon.png"
    icon_ico = ROOT / "build" / "cronus_icon.ico"
    try:
        (ROOT / "build").mkdir(parents=True, exist_ok=True)
        from PIL import Image

        img = Image.open(icon_png).convert("RGBA")
        img.save(icon_ico, format="ICO", sizes=[(256, 256), (128, 128), (64, 64), (48, 48), (32, 32), (16, 16)])
        print(f"[build] wrote icon {icon_ico}")
        return icon_ico
    except Exception as exc:
        print(f"[build] icon generation failed ({exc}); building without icon")
        return Path("")


def data_arg(src: str, dest: str) -> str:
    """PyInstaller --add-data uses ';' on Windows and ':' elsewhere."""
    return f"{src}{os.pathsep}{dest}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Build CronusLauncher.exe")
    parser.add_argument("--console", action="store_true", help="Keep a console window (default is windowed)")
    parser.add_argument("--windowed", action="store_true", help="No console window (default behavior; accepted for clarity)")
    parser.add_argument("--onedir", action="store_true", help="Build a folder layout instead of a single exe (fewer AV false positives)")
    parser.add_argument("--zip", action="store_true", help="Zip the dist output into dist/<name>-portable.zip")
    parser.add_argument("--name", default="CronusLauncher", help="Output exe name (default CronusLauncher)")
    parser.add_argument("--commit", default="", help="Override the embedded upstream commit SHA")
    args = parser.parse_args()
    if args.windowed:
        args.console = False

    commit = args.commit.strip() or resolve_commit()
    build_date = datetime.datetime.now(datetime.timezone.utc)
    write_build_info(commit, commit_date(commit))

    # A stale spec from a previous run would be reused by PyInstaller; drop it.
    stale_spec = ROOT / (args.name + ".spec")
    if stale_spec.exists():
        stale_spec.unlink()
        print(f"[build] removed stale spec {stale_spec.name}")

    icon = make_icon()
    version_file = make_version_file(build_date)

    pyinstaller_args = [
        "--noconfirm",
        "--clean",
        "--onedir" if args.onedir else "--onefile",
        "--console" if args.console else "--windowed",
        "--name", args.name,
        "--exclude-module", "tkinter",
        "--hidden-import", "pystray._win32",
        "--hidden-import", "httptools",
        "--hidden-import", "watchfiles",
        "--hidden-import", "websockets",
        "--add-data", data_arg(str(ROOT / "assets"), "assets"),
        "--add-data", data_arg(str(ROOT / "ui"), "ui"),
        "--add-data", data_arg(str(ROOT / "lua"), "lua"),
        "--add-data", data_arg(str(ROOT / "requirements.txt"), "."),
    ]
    if icon and str(icon) and icon.exists():
        pyinstaller_args += ["--icon", str(icon)]
    if version_file and str(version_file) and version_file.exists():
        pyinstaller_args += ["--version-file", str(version_file)]
    pyinstaller_args.append(str(ROOT / "main.py"))

    print(f"[build] running PyInstaller with: {' '.join(pyinstaller_args)}")
    from PyInstaller.__main__ import run

    run(pyinstaller_args)

    if args.onedir:
        out_dir = ROOT / "dist" / args.name
        exe_out = out_dir / (args.name + ".exe")
        if not exe_out.exists():
            print("[build] ERROR: expected output exe not found")
            return 1
        print(f"[build] done - folder output: {out_dir}")
        if args.zip:
            zip_base = ROOT / "dist" / f"{args.name}-portable"
            shutil.make_archive(str(zip_base), "zip", root_dir=ROOT / "dist", base_dir=args.name)
            print(f"[build] zipped -> {zip_base}.zip")
    else:
        exe_out = ROOT / "dist" / (args.name + ".exe")
        print(f"[build] done - output: {exe_out}")
        if args.zip:
            shutil.copy2(exe_out, ROOT / "dist" / f"{args.name}-portable.zip")
            print(f"[build] copied -> {ROOT / 'dist' / (args.name + '-portable.zip')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
