import {api} from './runtime/api.js';
import {createStatusRuntime} from './runtime/status.js';
import {bucket,isBlocked,counts as countAccounts,filterAccounts,rowStatusLabel,rowStatusTitle} from './runtime/accountStatus.js';
import {renderAccountRows} from './components/accountsTable.js';
import {createFeedback} from './components/feedback.js';
import {bindDashboardEvents} from './events/bindings.js';
import {renderSettingsPanel,renderPerformancePanel,renderGraphicsPanel,renderWindowSizePanel,renderCpuLimiterPanel,renderTroubleshootPanel,resetGamePanel,resetQueuePanel,resetPerformancePanel,resetGraphicsPanel,resetWindowSizePanel,resetCpuLimiterPanel,saveGamePanel,saveQueuePanel,savePerformancePanel,saveGraphicsPanel,saveWindowSizePanel,saveCpuLimiterPanel} from './panels/settingsPanels.js';
const $=id=>document.getElementById(id);
let STATUS={},ACCOUNTS=[],ACCOUNT_CONFIG=[],CONFIG={},PERF={},GRAPHICS={},WINDOW_SIZE={},CPU_LIMITER={},TROUBLESHOOT={},GAME_PLACE_CACHE={},AVATARS={},avatarLoadedKey='',VIEW=localStorage.getItem('rg_view')||'accounts',selectedUser=localStorage.getItem('rg_selected')||'',commandBusy=false,configLoadedAt=0,gameLookupTimer=0,LAST_STATUS_REVISION=-1,LAST_STATUS_UPDATED_AT=0,STATUS_REQUEST_SEQ=0,STATUS_APPLIED_SEQ=0,SETTINGS_DIRTY={},RUNNING_CLOCK_ACTIVE=false,RUNNING_CLOCK_BASE_SECONDS=0,RUNNING_CLOCK_BASE_MS=Date.now();
const WINDOW_SIZE_PRESETS={'320x240':[320,240],'480x360':[480,360],'640x480':[640,480],'800x600':[800,600],'1024x768':[1024,768],'1280x720':[1280,720],'1600x900':[1600,900],'1920x1080':[1920,1080]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const {toast,modal,closeModal,cardIcon}=createFeedback({$,esc});
const lower=s=>String(s||'').toLowerCase();
const num=v=>Number(v||0)||0;
function uptimeSeconds(value){if(typeof value==='number')return Math.max(0,Math.floor(value));const s=String(value||'').trim();if(!s)return 0;const parts=s.split(':').map(x=>Number(x)||0);if(parts.length===3)return parts[0]*3600+parts[1]*60+parts[2];if(parts.length===2)return parts[0]*60+parts[1];return Number(s)||0}
function shortDuration(seconds){let s=Math.max(0,Math.floor(seconds||0)),h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60),r=s%60;if(h)return `${h}h ${m}m`;if(m)return `${m}m ${r}s`;return `${r}s`}
function syncRunningClock(){RUNNING_CLOCK_ACTIVE=!!STATUS.running;RUNNING_CLOCK_BASE_SECONDS=RUNNING_CLOCK_ACTIVE?uptimeSeconds(STATUS.uptime):0;RUNNING_CLOCK_BASE_MS=Date.now();renderRunningClock()}
function renderRunningClock(){const el=$('h-running-time');if(!el)return;const elapsed=RUNNING_CLOCK_ACTIVE?RUNNING_CLOCK_BASE_SECONDS+Math.floor((Date.now()-RUNNING_CLOCK_BASE_MS)/1000):0;el.textContent=`Running: ${shortDuration(elapsed)}`}
function acceptStatus(nextStatus,seq=0){const rev=Number(nextStatus?.status_revision??-1),updated=Number(nextStatus?.status_updated_at??0);if(seq&&seq<STATUS_APPLIED_SEQ)return false;if(rev>=0&&LAST_STATUS_REVISION>rev){if(updated&&updated>LAST_STATUS_UPDATED_AT){LAST_STATUS_REVISION=-1}else{return false}}if(seq)STATUS_APPLIED_SEQ=seq;if(rev>=0)LAST_STATUS_REVISION=rev;if(updated)LAST_STATUS_UPDATED_AT=updated;STATUS=nextStatus||{};return true}
function dirty(view){return !!SETTINGS_DIRTY[view]}
function syncToggleLabels(){document.querySelectorAll('.toggle-row input[type="checkbox"]').forEach(input=>{const text=input.parentElement?.querySelector('span');if(text)text.textContent=input.checked?'Enabled':'Disabled'})}
function setCompactToggle(inputId,labelId,controlsId,onLabel){const enabled=!!$(inputId)?.checked,label=$(labelId),controls=$(controlsId);if(label)label.textContent=enabled?onLabel:'Disabled';if(controls)controls.hidden=!enabled;return enabled}
function updateSaveState(view){const saveMap={game:'game-save',queue:'queue-save',performance:'fps-save',graphics:'graphics-save','window-size':'window-size-save','cpu-limiter':'cpu-save'},resetMap={game:'game-reset',queue:'queue-reset',performance:'fps-reset',graphics:'graphics-reset','window-size':'window-size-reset','cpu-limiter':'cpu-reset'},isDirty=dirty(view),save=$(saveMap[view]),reset=$(resetMap[view]);if(save){save.classList.toggle('settings-dirty',isDirty);save.hidden=!isDirty}if(reset)reset.hidden=!isDirty;syncToggleLabels()}
function markDirty(view){SETTINGS_DIRTY[view]=true;updateSaveState(view)}
function clearDirty(view){delete SETTINGS_DIRTY[view];updateSaveState(view)}
function clearDirtyMany(...views){views.forEach(clearDirty)}
function unsavedSettings(){return Object.keys(SETTINGS_DIRTY)}
function requireSavedSettings(){const pending=unsavedSettings();if(!pending.length)return true;toast('Save changes first.');return false}
function initials(s){return String(s||'?').split(/[^a-zA-Z0-9]+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function cfgFor(user){const key=lower(user);return ACCOUNT_CONFIG.find(a=>lower(a.username)===key)||{}}
function selected(){return ACCOUNTS.find(a=>a.username===selectedUser)||ACCOUNTS[0]||null}
function counts(){return countAccounts(ACCOUNTS)}
function filtered(){return filterAccounts(ACCOUNTS,$('account-search')?.value||'',cfgFor)}
async function loadAccountsConfig(force=false){if(!force&&Date.now()-configLoadedAt<4000&&ACCOUNT_CONFIG.length)return ACCOUNT_CONFIG;const data=await api('/accounts');if(Array.isArray(data))ACCOUNT_CONFIG=data;configLoadedAt=Date.now();return ACCOUNT_CONFIG}
function accountUserId(a){const cfg=cfgFor(a.username);return String(a.user_id||a.cookie_user_id||cfg.user_id||cfg.cookie_user_id||'').trim()}
function avatarHtml(a,display){const uid=accountUserId(a),src=uid?AVATARS[uid]:'';const fallback=esc(initials(display));if(src)return`<span class="avatar-wrap"><img class="avatar-img" src="${esc(src)}" alt="" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="avatar" hidden>${fallback}</span></span>`;return`<span class="avatar-wrap"><span class="avatar">${fallback}</span></span>`}
async function loadAvatars(){const ids=[...new Set(ACCOUNTS.map(accountUserId).filter(Boolean))].sort();const key=ids.join(',');if(!ids.length||key===avatarLoadedKey)return;avatarLoadedKey=key;const r=await api('/accounts/avatars?user_ids='+encodeURIComponent(key));if(r&&r.avatars)AVATARS={...AVATARS,...r.avatars};renderAccountsTable()}
async function loadConfig(){CONFIG=await api('/config');renderSettings();renderWindowSize();const place=CONFIG.game_place_id||placeFromPrivate(CONFIG.game_private_server_url||'');if(place)loadGamePlace(place,true).catch(()=>{});return CONFIG}
async function loadPerformance(){try{PERF=await api('/performance/fps-limiter');renderPerformance();return PERF}catch(e){PERF={ok:false,msg:e.message};renderPerformance();return PERF}}
async function loadGraphics(){try{GRAPHICS=await api('/performance/graphics');renderGraphics();return GRAPHICS}catch(e){GRAPHICS={ok:false,msg:e.message};renderGraphics();return GRAPHICS}}
async function loadWindowSize(){try{WINDOW_SIZE=await api('/performance/window-size');renderWindowSize();return WINDOW_SIZE}catch(e){WINDOW_SIZE={ok:false,msg:e.message};renderWindowSize();return WINDOW_SIZE}}
async function loadCpuLimiter(){try{CPU_LIMITER=await api('/performance/cpu-limiter');renderCpuLimiter();return CPU_LIMITER}catch(e){CPU_LIMITER={ok:false,msg:e.message,rows:[]};renderCpuLimiter();return CPU_LIMITER}}
async function loadTroubleshoot(){try{TROUBLESHOOT=await api('/troubleshoot/roblox-install');renderTroubleshoot();return TROUBLESHOOT}catch(e){TROUBLESHOOT={ok:false,msg:e.message,job:{state:'Failed',progress:e.message}};renderTroubleshoot();return TROUBLESHOOT}}
function resetGameSettings(){return resetGamePanel(panelCtx())}
function resetQueueSettings(){return resetQueuePanel(panelCtx())}
function resetPerformanceSettings(){return resetPerformancePanel(panelCtx())}
function resetGraphicsSettings(){return resetGraphicsPanel(panelCtx())}
function resetWindowSizeSettings(){return resetWindowSizePanel(panelCtx())}
function resetCpuLimiterSettings(){return resetCpuLimiterPanel(panelCtx())}
function robloxInstallConfirm(action){const copy={uninstall:['Uninstall Roblox','Removes all Roblox files from this PC.','Uninstall'],latest:['Download latest','Wipes Roblox, then installs latest LIVE player.','Download']}[action];if(!copy)return toast('Unknown action');modal(copy[0],`<div class="choice-grid" style="grid-template-columns:1fr"><div class="choice" style="cursor:default">${cardIcon('install')}<strong>${copy[0]}</strong><span class="hint">${copy[1]}</span></div></div>`,`<button class="btn ghost" id="install-back">Back</button><button class="btn ${action==='uninstall'?'danger':'good'}" id="install-confirm">${copy[2]}</button>`);$('install-back').onclick=closeModal;$('install-confirm').onclick=()=>runRobloxInstall(action)}
async function runRobloxInstall(action){try{const path=action==='uninstall'?'/troubleshoot/roblox-install/uninstall':'/troubleshoot/roblox-install/latest';const r=await api(path,'POST',{});closeModal();if(!r.ok)return toast(r.msg||'Install blocked');toast(r.msg||'Job started');await loadTroubleshoot()}catch(e){toast(e.message)}}
function setView(view){const allowed={accounts:1,game:1,queue:1,performance:1,graphics:1,'window-size':1,'cpu-limiter':1,troubleshoot:1};VIEW=allowed[view]?view:'accounts';localStorage.setItem('rg_view',VIEW);document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+VIEW));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===VIEW));if(VIEW==='troubleshoot')loadTroubleshoot();if(VIEW==='performance')loadPerformance();if(VIEW==='graphics')loadGraphics();if(VIEW==='window-size')loadWindowSize();if(VIEW==='cpu-limiter')loadCpuLimiter();render()}
function render(){ACCOUNTS=Array.isArray(STATUS.accounts)?STATUS.accounts:[];if(!selectedUser&&ACCOUNTS[0])selectedUser=ACCOUNTS[0].username;renderTop();renderAccountsTable();renderSettings();renderPerformance();renderGraphics();renderWindowSize();renderCpuLimiter();renderTroubleshoot();syncToggleLabels();Object.keys(SETTINGS_DIRTY).forEach(updateSaveState)}
function renderTop(){const c=counts(),running=!!STATUS.running;$('nav-accounts-count').textContent=c.all;$('h-online').textContent=c.online;$('h-queued').textContent=c.queued;syncRunningClock();$('guard-btn').innerHTML=running?'<svg class="guard-icon stop" aria-hidden="true" viewBox="0 0 24 24"><rect x="7" y="7" width="10" height="10" rx="1.5"/></svg><span>STOP</span>':'<svg class="guard-icon" aria-hidden="true" viewBox="0 0 24 24"><path d="M7 5v14l11-7z"/></svg><span>START</span>';$('guard-btn').className=running?'btn danger guard-action':'btn good guard-action';$('guard-btn').disabled=commandBusy||(!STATUS.can_start&&!STATUS.can_stop)}
function renderAccountsTable(){if(document.activeElement?.classList.contains('desc-input'))return;const rows=filtered();$('accounts-table').innerHTML=renderAccountRows({rows,selectedUser,cfgFor,bucket,isBlocked,rowStatusLabel,rowStatusTitle,avatarHtml,esc})}
function placeFromPrivate(url){const m=String(url||'').match(/roblox\.com\/games\/(\d+)/i);return m?m[1]:''}
function renderGameMap(place='',info=null,msg=''){const card=$('game-map-card');if(!card)return;const id=String(place||'').trim();const data=info||GAME_PLACE_CACHE[id];if(data){card.className='map-card';card.innerHTML=`<img class="map-thumb" src="${esc(data.image_url||'')}" alt=""><div><div class="map-name">${esc(data.name||('Place '+id))}</div><div class="map-byline">${esc(data.builder?('by '+data.builder):'Roblox experience')}</div><div class="map-status">Place ID ${esc(data.place_id||id)}${data.universe_id?' / Universe '+esc(data.universe_id):''}</div></div>`;return}card.className='map-card empty';card.innerHTML=`<div>${esc(msg|| (id?'Click Lookup.':'Enter Place ID.'))}</div>`}
async function loadGamePlace(place,quiet=false){const id=String(place||'').trim();if(!id){renderGameMap('',null);return null}renderGameMap(id,null,'Loading Roblox map details...');const data=await api('/game/place/'+encodeURIComponent(id));GAME_PLACE_CACHE[id]=data;renderGameMap(id,data);if(!quiet)toast(data.name||'place loaded');return data}
function panelCtx(){return{$,api,CONFIG,PERF,GRAPHICS,WINDOW_SIZE,CPU_LIMITER,TROUBLESHOOT,WINDOW_SIZE_PRESETS,dirty,setCompactToggle,updateSaveState,clearDirty,toast,esc,loadConfig,loadGraphics,manualSnapshot,renderPerformance,renderGraphics,renderWindowSize,renderCpuLimiter}}
function renderSettings(){return renderSettingsPanel(panelCtx())}
function renderPerformance(next){if(next)PERF=next;return renderPerformancePanel(panelCtx())}
function renderGraphics(next){if(next)GRAPHICS=next;return renderGraphicsPanel(panelCtx())}
function renderWindowSize(next){if(next)WINDOW_SIZE=next;return renderWindowSizePanel(panelCtx())}
function renderCpuLimiter(next){if(next)CPU_LIMITER=next;return renderCpuLimiterPanel(panelCtx())}
function renderTroubleshoot(){return renderTroubleshootPanel(panelCtx())}
function logTime(ts){if(!ts)return'--:--:--';return new Date(Number(ts)*1000).toLocaleTimeString('en-GB',{hour12:false})}
function logAccountName(e){const p=e?.payload||{};return String(e?.account||p.account||p.account_id||p.display||'System')}
function logSummaryCounts(){const out={running:0,verify:0,recovery:0,failed:0};ACCOUNTS.forEach(a=>{const st=String(a.public_state||a.state||'').toUpperCase(),rs=String(a.runtime_state||'').toUpperCase(),b=bucket(a);if(st==='IN_GAME'||rs==='RUNNING')out.running++;if(['VERIFY','LAUNCHING'].includes(st)||['JOINING','STARTING'].includes(rs))out.verify++;if(['NETWORK_LOST','COOLDOWN'].includes(st)||['RECOVERING','BACKOFF'].includes(rs)||['network','recovery','cooldown'].includes(b))out.recovery++;if(['FAILED','CRASH'].includes(st)||['blocked','finished'].includes(b))out.failed++});return out}
function renderLogSummary(){const c=logSummaryCounts();[['running',c.running],['verify',c.verify],['recovery',c.recovery],['failed',c.failed]].forEach(([k,v])=>{const el=$('log-sum-'+k);if(el)el.textContent=v})}
function logRawText(e){const p=e?.payload||{};return lower([e?.event_type,e?.reason,p.msg,p.reason,p.step,p.status,p.event_type,p.public_state,p.runtime_state].filter(Boolean).join(' '))}
function normalizeLogEvent(e){const p=e?.payload||{},text=logRawText(e),sev=lower(e?.severity||p.severity||'info'),type=lower(e?.event_type||p.event_type||''),reason=lower(e?.reason||p.reason||''),msg=String(p.msg||'').trim();let kind='info',icon='IN',label='INFO';if(sev.includes('critical')||sev.includes('error')||type.includes('failed')||reason.includes('failed')){kind='error';icon='X';label='ERROR'}else if(sev.includes('warn')||type.includes('reject')||reason.includes('stale')){kind='warn';icon='!';label='WARN'}else if(text.includes('recovery')||text.includes('rejoin')||text.includes('disconnect')||text.includes('cooldown')||text.includes('network')){kind='recovery';icon='RJ';label='RECOVERY'}else if(text.includes('state')||text.includes('transition')){kind='state';icon='ST';label='STATE'}else if(text.includes('launch')){kind='state';icon='LA';label='LAUNCH'}else if(text.includes('verify')||text.includes('join')){kind='state';icon='VF';label='VERIFY'}else if(text.includes('pid')||text.includes('process')||text.includes('bound')||text.includes('binding')){kind='info';icon='PID';label='PROC'}else if(sev.includes('success')||text.includes('in_game')||text.includes('online')){kind='success';icon='OK';label='SUCCESS'}const noise=['owned_mutation','status_revision','revision_bumped','transaction_step','rejoin_transaction_update','heartbeat','auto_window_arrange_cycle','auto_process_priority_applied'].some(x=>text.includes(x));const important=!noise&&(kind!=='info'||['LAUNCH','VERIFY','PROC','STATE','SUCCESS'].includes(label));let title=msg||'';if(!title){const account=logAccountName(e);if(label==='LAUNCH')title=`${account} -> Roblox started`;else if(label==='VERIFY')title=`${account} -> waiting verification`;else if(label==='PROC')title=`PID attached${e?.pid?': '+e.pid:''}`;else if(label==='RECOVERY')title=`${account} -> ${String(e?.reason||p.reason||'recovery').replace(/_/g,' ')}`;else if(label==='STATE'){const old=p.old||p.old_runtime||'',nw=p.new||p.new_runtime||e?.public_state||e?.runtime_state||'';title=old&&nw?`${account}: ${old} -> ${nw}`:`${account} -> state update`}else if(label==='SUCCESS')title=`${account} -> success`;else if(label==='ERROR')title=`${account} -> ${String(e?.reason||p.reason||'error').replace(/_/g,' ')}`;else title=`${account} -> ${String(e?.event_type||p.event_type||'event').replace(/_/g,' ')}`}const sub=[e?.public_state||p.public_state||'',e?.runtime_state||p.runtime_state||'',e?.reason||p.reason||'',e?.pid?`PID ${e.pid}`:''].filter(Boolean).join(' / ');return{event:e,payload:p,id:String(e?.id||`${e?.ts||0}-${type}-${logAccountName(e)}`),kind,icon,label,title,sub,noise,important,account:logAccountName(e),tx:String(e?.rejoin_transaction_id||p.rejoin_transaction_id||p.transaction_id||''),ts:Number(e?.ts||0)}}
function logVisible(n){if(LOG_FILTER==='debug')return true;if(LOG_FILTER==='info')return !n.noise;if(LOG_FILTER==='raw')return false;return n.important}
function renderLogInspector(items){const box=$('logs-inspector');if(!box)return;let selected=items.find(n=>n.id===LOG_SELECTED_ID)||items[items.length-1];if(!selected){box.innerHTML='<div class="log-inspector-empty">Select an event to inspect metadata.</div>';return}LOG_SELECTED_ID=selected.id;const e=selected.event,meta={event_type:e.event_type||'',reason:e.reason||'',account:selected.account,pid:e.pid||'',runtime_state:e.runtime_state||'',public_state:e.public_state||'',runtime_generation:e.runtime_generation||0,recovery_generation:e.recovery_generation||0,command_generation:e.command_generation||0,session_id:e.session_id||'',transaction_id:e.rejoin_transaction_id||'',severity:e.severity||'',payload:e.payload||{}};box.innerHTML=`<div class="log-inspector-title">${esc(selected.label)} metadata</div><div class="log-meta-grid"><div class="log-meta-item"><span>Account</span><strong>${esc(meta.account||'System')}</strong></div><div class="log-meta-item"><span>PID</span><strong>${esc(meta.pid||'-')}</strong></div><div class="log-meta-item"><span>Runtime</span><strong>${esc(meta.runtime_state||'-')}</strong></div><div class="log-meta-item"><span>Public</span><strong>${esc(meta.public_state||'-')}</strong></div></div><pre class="log-json">${esc(JSON.stringify(meta,null,2))}</pre>`}
function renderLogs(){renderLogSummary();document.querySelectorAll('[data-log-filter]').forEach(b=>b.classList.toggle('active',b.dataset.logFilter===LOG_FILTER));const rawMode=LOG_FILTER==='raw',obs=$('log-observability'),raw=$('logs-raw'),timeline=$('logs-timeline');if(obs)obs.hidden=rawMode;if(raw)raw.hidden=!rawMode;if(rawMode){$('logbox').innerHTML=(LOGS.length?LOGS:['No raw log lines yet.']).map(line=>`<div class="log-line">${esc(line)}</div>`).join('');return}if(!timeline)return;const items=RUNTIME_EVENTS.slice().sort((a,b)=>(Number(a.ts||0)-Number(b.ts||0))).map(normalizeLogEvent).filter(logVisible).slice(-220);if(!items.length){timeline.innerHTML='<div class="log-inspector-empty" style="padding:14px">No important runtime events yet.</div>';renderLogInspector([]);return}const groups=[];items.forEach(n=>{const key=n.account+'|'+(n.tx||'runtime');let g=groups.find(x=>x.key===key);if(!g){const account=ACCOUNTS.find(a=>lower(a.username)===lower(n.account)||lower(a.display)===lower(n.account));g={key,account:n.account,state:account?rowStatusLabel(account,bucket(account)):(n.event.public_state||n.event.runtime_state||''),items:[]};groups.push(g)}g.items.push(n)});timeline.innerHTML=groups.map(g=>`<section class="log-group"><div class="log-group-head"><div class="log-group-name">${esc(g.account||'System')}</div><div class="log-group-state">${esc(g.state||'Runtime')}</div></div>${g.items.map(n=>`<div class="log-event event-${n.kind} ${n.id===LOG_SELECTED_ID?'selected':''}" data-event-id="${esc(n.id)}"><div class="log-time">${esc(logTime(n.ts))}</div><div class="log-icon">${esc(n.icon)}</div><div><div class="log-event-title">[${esc(n.label)}] ${esc(n.title)}</div><div class="log-event-sub">${esc(n.sub||'metadata hidden')}</div></div></div>`).join('')}</section>`).join('');renderLogInspector(items)}
function setStreamState(text,cls='stream'){const state=$('stream-state');if(state){state.textContent=text;state.className=cls}}
const statusRuntime=createStatusRuntime({api,nextSequence:()=>++STATUS_REQUEST_SEQ,acceptStatus,setStreamState,loadAccountsConfig,render,loadAvatars,toast});
async function manualSnapshot(){return statusRuntime.manualSnapshot()}
async function toggleGuard(){if(commandBusy)return;if(!STATUS.running&&!requireSavedSettings())return;commandBusy=true;renderTop();try{const r=await api(STATUS.running?'/stop':'/start','POST');toast(r.msg||'command sent');await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderTop()}}
async function saveAccounts(next,msg='accounts saved'){const r=await api('/accounts','POST',next);if(!r.ok)throw new Error(r.msg||'Save failed');ACCOUNT_CONFIG=next;configLoadedAt=Date.now();toast(msg);await manualSnapshot()}
async function saveDescription(user,value){const current=await loadAccountsConfig(true),key=lower(user);const next=current.map(a=>lower(a.username)===key?{...a,description:value}:a);await saveAccounts(next,'Saved')}
async function reloadCookies(){if(commandBusy)return;commandBusy=true;renderTop();try{const r=await api('/accounts/reload','POST',{});ACCOUNT_CONFIG=[];configLoadedAt=0;toast(r.msg||'Reloaded cookies');await loadAccountsConfig(true);await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderTop()}}
function deleteAccount(user){if(!user)return;const a=ACCOUNTS.find(x=>x.username===user)||{},cfg=cfgFor(user),display=a.display||cfg.alias||user;modal('Delete Account',`<div class="choice-grid" style="grid-template-columns:1fr"><div class="choice" style="cursor:default">${cardIcon('delete')}<strong>Delete <span class="danger-name">${esc(display)}</span></strong><span class="hint">Removes this account and cookie.</span></div></div>`,`<button class="btn ghost" id="delete-back">Back</button><button class="btn danger" id="delete-confirm">Delete Account</button>`);$('delete-back').onclick=closeModal;$('delete-confirm').onclick=()=>confirmDeleteAccount(user)}
async function confirmDeleteAccount(user){if(!user)return;commandBusy=true;renderAccountsTable();try{const current=await loadAccountsConfig(true),key=lower(user),next=current.filter(a=>lower(a.username)!==key);await saveAccounts(next,'Deleted');if(lower(selectedUser)===key){selectedUser=next[0]?.username||'';selectedUser?localStorage.setItem('rg_selected',selectedUser):localStorage.removeItem('rg_selected')}closeModal()}catch(e){toast(e.message)}finally{commandBusy=false;renderAccountsTable()}}
async function launchAccount(user){if(!user)return;if(!requireSavedSettings())return;const account=ACCOUNTS.find(a=>a.username===user);if(account&&isBlocked(account))return toast(account.blocked_reason||'Reimport correct cookie first');const cfg=cfgFor(user);const body={place_id:cfg.place_id||CONFIG.game_place_id||'',global_vip_link:CONFIG.game_private_server_url||'',auto_create_private_server_enabled:!!CONFIG.auto_create_private_server_enabled,auto_create_private_server_free_only:CONFIG.auto_create_private_server_free_only!==false,multi_roblox:CONFIG.multi_roblox_enabled!==false};try{const r=await api('/account/'+encodeURIComponent(user)+'/launch','POST',body);toast(r.msg||'launch requested');await manualSnapshot()}catch(e){toast(e.message)}}
async function dedupeAccount(user){if(!user)return;try{const r=await api('/account/'+encodeURIComponent(user)+'/kill-duplicate','POST',{});toast('duplicates closed: '+(r.count||0));await manualSnapshot()}catch(e){toast(e.message)}}
function closeAllRoblox(){if(commandBusy)return;modal('Close All Roblox',`<div class="choice-grid" style="grid-template-columns:1fr"><div class="choice" style="cursor:default">${cardIcon('close')}<strong>Close Roblox only</strong><span class="hint">Closes every Roblox window. Argus stays running.</span></div></div>`,`<button class="btn ghost" id="close-all-back">Back</button><button class="btn danger" id="close-all-confirm">Close All Roblox</button>`);$('close-all-back').onclick=closeModal;$('close-all-confirm').onclick=confirmCloseAllRoblox}
async function confirmCloseAllRoblox(){if(commandBusy)return;commandBusy=true;renderTop();try{const r=await api('/roblox/close-all','POST',{});closeModal();toast(r.msg||'Roblox closed');await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderTop()}}
async function verifyAccount(user){if(!user)return;if(!confirm('Verify and finish '+user+'?'))return;commandBusy=true;renderAccountsTable();try{const r=await api('/account/'+encodeURIComponent(user)+'/verify','POST');toast(r.msg||'verified');await loadAccountsConfig(true);await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderAccountsTable()}}
function openAdd(){openCookie()}
function openCookie(){modal('Import Cookies',`<div class="field"><div class="hint">One cookie per line.</div><textarea id="cookie-lines" class="textarea" placeholder="user1:pass1:_|WARNING:...&#10;_|WARNING:cookie-only..."></textarea></div>`,`<button class="btn ghost" id="cookie-cancel">Cancel</button><button class="btn good" id="cookie-add">Add Accounts</button>`);$('cookie-cancel').onclick=closeModal;$('cookie-add').onclick=submitCookies}
function parseCookieLine(line){const idx=line.indexOf('_|WARNING:');if(idx>=0)return{username:(line.slice(0,idx).split(':')[0]||'').trim(),cookie:line.slice(idx).trim()};const parts=line.split(':');if(parts.length>=3)return{username:parts[0].trim(),cookie:parts.slice(2).join(':').trim()};return{username:'',cookie:line.trim()}}
async function submitCookies(){const lines=$('cookie-lines').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const r=await api('/accounts/import','POST',{kind:'cookies',lines});toast(`Imported (${r.imported||0})`);closeModal();await loadAccountsConfig(true);await manualSnapshot()}
async function saveGame(){return saveGamePanel(panelCtx())}
async function lookupGame(){let place=$('game-place').value.trim();const url=$('game-private').value.trim();$('game-lookup-result').textContent='';if(!place&&url){place=placeFromPrivate(url);if(!place){try{const r=await api('/account/_/test-vip','POST',{vip_url:url});if(r.ok&&r.place_id)place=r.place_id;$('game-lookup-result').textContent=r.ok?`VIP link parsed: Place ID ${r.place_id}`:(r.msg||'Invalid URL')}catch(e){$('game-lookup-result').textContent=e.message}}if(place)$('game-place').value=place}if(!place)return toast('Place ID required');try{const data=await loadGamePlace(place,false);$('game-lookup-result').textContent=data?.name?`${data.name} loaded`:'Map loaded'}catch(e){renderGameMap(place,null,e.message);$('game-lookup-result').textContent=e.message}}
async function saveQueue(){return saveQueuePanel(panelCtx())}
async function savePerformance(){PERF=await savePerformancePanel(panelCtx())}
async function saveGraphics(){GRAPHICS=await saveGraphicsPanel(panelCtx())}
async function saveWindowSize(){WINDOW_SIZE=await saveWindowSizePanel(panelCtx())}
async function saveCpuLimiter(){CPU_LIMITER=await saveCpuLimiterPanel(panelCtx())}
function connectStream(){return statusRuntime.connectStream()}
bindDashboardEvents({$,document,syncToggleLabels,setView,toggleGuard,openAdd,reloadCookies,closeAllRoblox,closeModal,renderAccountsTable,resetGameSettings,saveGame,lookupGame,resetPerformanceSettings,savePerformance,resetGraphicsSettings,saveGraphics,resetWindowSizeSettings,saveWindowSize,resetCpuLimiterSettings,saveCpuLimiter,resetQueueSettings,saveQueue,robloxInstallConfirm,markDirty,renderSettings,renderPerformance,renderGraphics,renderWindowSize,renderCpuLimiter,gameLookupTimer:()=>gameLookupTimer,setGameLookupTimer:v=>{gameLookupTimer=v},renderGameMap,loadGamePlace,placeFromPrivate,deleteAccount,launchAccount,dedupeAccount,selectUser:user=>{selectedUser=user;localStorage.setItem('rg_selected',selectedUser)},saveDescription,toast});
(async function init(){setView(VIEW);await loadConfig();await loadPerformance();await loadGraphics();await loadWindowSize();await loadCpuLimiter();await loadTroubleshoot();await loadAccountsConfig(true);connectStream();setInterval(renderRunningClock,1000);setInterval(()=>{if(VIEW==='troubleshoot')loadTroubleshoot();if(VIEW==='cpu-limiter')loadCpuLimiter()},3500)})();
