import {api} from './runtime/api.js';
import {createStatusRuntime} from './runtime/status.js';
import {bucket,isBlocked,isCaptcha,counts as countAccounts,filterAccounts,label as bucketLabel,rowStatusLabel,rowStatusTitle} from './runtime/accountStatus.js';
import {renderAccountRows} from './components/accountsTable.js';
import {createFeedback} from './components/feedback.js';
import {applySolarStaticIcons,solarIcon} from './components/icons.js';
import {bindDashboardEvents} from './events/bindings.js';
import {renderSettingsPanel,renderPerformancePanel,renderRamPanel,renderGraphicsPanel,renderWindowSizePanel,renderCpuLimiterPanel,renderTroubleshootPanel,resetGamePanel,resetQueuePanel,resetPerformancePanel,resetRamPanel,resetGraphicsPanel,resetWindowSizePanel,resetCpuLimiterPanel,saveGamePanel,saveQueuePanel,savePerformancePanel,saveRamPanel,saveGraphicsPanel,saveWindowSizePanel,saveCpuLimiterPanel} from './panels/settingsPanels.js';
const $=id=>document.getElementById(id);
let STATUS={},ACCOUNTS=[],ACCOUNT_CONFIG=[],CONFIG={},PERF={},GRAPHICS={},WINDOW_SIZE={},CPU_LIMITER={},TROUBLESHOOT={},GAME_PLACE_CACHE={},AVATARS={},avatarLoadedKey='',VIEW=localStorage.getItem('rg_view')||'accounts',selectedUser=localStorage.getItem('rg_selected')||'',ACCOUNT_FILTER=localStorage.getItem('rg_account_filter')||'all',commandBusy=false,configLoadedAt=0,gameLookupTimer=0,LAST_STATUS_REVISION=-1,LAST_STATUS_UPDATED_AT=0,STATUS_REQUEST_SEQ=0,STATUS_APPLIED_SEQ=0,SETTINGS_DIRTY={},RUNNING_CLOCK_ACTIVE=false,RUNNING_CLOCK_BASE_SECONDS=0,RUNNING_CLOCK_BASE_MS=Date.now();
const WINDOW_SIZE_PRESETS={'320x240':[320,240],'480x360':[480,360],'640x480':[640,480],'800x600':[800,600],'1024x768':[1024,768],'1280x720':[1280,720],'1600x900':[1600,900],'1920x1080':[1920,1080]};
const ACCOUNT_FILTERS=['all','online','queued'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const {toast,modal,closeModal,cardIcon}=createFeedback({$,esc});
const lower=s=>String(s||'').toLowerCase();
function uptimeSeconds(value){if(typeof value==='number')return Math.max(0,Math.floor(value));const s=String(value||'').trim();if(!s)return 0;const parts=s.split(':').map(x=>Number(x)||0);if(parts.length===3)return parts[0]*3600+parts[1]*60+parts[2];if(parts.length===2)return parts[0]*60+parts[1];return Number(s)||0}
function shortDuration(seconds){let s=Math.max(0,Math.floor(seconds||0)),h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60),r=s%60;if(h)return `${h}h ${m}m`;if(m)return `${m}m ${r}s`;return `${r}s`}
function syncRunningClock(){RUNNING_CLOCK_ACTIVE=!!STATUS.running;RUNNING_CLOCK_BASE_SECONDS=RUNNING_CLOCK_ACTIVE?uptimeSeconds(STATUS.uptime):0;RUNNING_CLOCK_BASE_MS=Date.now();renderRunningClock()}
function renderRunningClock(){const el=$('h-running-time');if(!el)return;const elapsed=RUNNING_CLOCK_ACTIVE?RUNNING_CLOCK_BASE_SECONDS+Math.floor((Date.now()-RUNNING_CLOCK_BASE_MS)/1000):0;el.textContent=`Running: ${shortDuration(elapsed)}`}
function acceptStatus(nextStatus,seq=0){const rev=Number(nextStatus?.status_revision??-1),updated=Number(nextStatus?.status_updated_at??0);if(seq&&seq<STATUS_APPLIED_SEQ)return false;if(rev>=0&&LAST_STATUS_REVISION>rev){if(updated&&updated>LAST_STATUS_UPDATED_AT){LAST_STATUS_REVISION=-1}else{return false}}if(seq)STATUS_APPLIED_SEQ=seq;if(rev>=0)LAST_STATUS_REVISION=rev;if(updated)LAST_STATUS_UPDATED_AT=updated;STATUS=nextStatus||{};return true}
function dirty(view){return !!SETTINGS_DIRTY[view]}
function valueOf(id){return String($(id)?.value??'').trim()}
function checked(id){return !!$(id)?.checked}
function numValue(id,fallback=0){const n=Number($(id)?.value);return Number.isFinite(n)?n:fallback}
function savedNum(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback}
function saveNumValue(id,fallback=0){const n=Number($(id)?.value);return n||fallback}
function sameNum(a,b){return Number(a)===Number(b)}
function normalizeRamLimitValue(value){const parsed=Number(value);if(!Number.isFinite(parsed))return 8192;return Math.max(512,Math.min(Math.round(parsed),65536))}
function currentRamLimit(){const preset=valueOf('ram-limit-preset')||'8192';return preset==='custom'?normalizeRamLimitValue(valueOf('ram-limit-custom')||8192):normalizeRamLimitValue(preset)}
function cpuRowsFromDom(){return Array.from(document.querySelectorAll('#cpu-account-rows tr')).map(row=>{const enabled=row.querySelector('.cpu-row-enabled'),limit=row.querySelector('.cpu-row-limit'),user=enabled?.dataset.user||limit?.dataset.user||'',limitValue=Number(limit?.value);return user?{username:user.toLowerCase(),enabled:!!enabled?.checked,limit_percent:limitValue||20}:null}).filter(Boolean).sort((a,b)=>a.username.localeCompare(b.username))}
function cpuRowsFromState(){return (Array.isArray(CPU_LIMITER.rows)?CPU_LIMITER.rows:[]).map(row=>({username:String(row.username||'').toLowerCase(),enabled:!!row.enabled,limit_percent:savedNum(row.limit_percent??CPU_LIMITER.default_limit_percent,20)})).filter(row=>row.username).sort((a,b)=>a.username.localeCompare(b.username))}
function sameCpuRows(a,b){if(a.length!==b.length)return false;return a.every((row,index)=>row.username===b[index].username&&row.enabled===b[index].enabled&&sameNum(row.limit_percent,b[index].limit_percent))}
function settingsChanged(view){try{switch(view){case'game':return valueOf('game-private')!==String(CONFIG.game_private_server_url||'')||valueOf('game-place')!==String(CONFIG.game_place_id||'')||checked('game-auto-private-enabled')!==!!CONFIG.auto_create_private_server_enabled||checked('game-multi-roblox')!==(CONFIG.multi_roblox_enabled!==false);case'queue':return !sameNum(saveNumValue('queue-max',1),savedNum(CONFIG.max_concurrent_accounts??40,40))||!sameNum(saveNumValue('queue-duration',0),savedNum(CONFIG.queue_duration_seconds??15,15))||!sameNum(saveNumValue('queue-delay',0),savedNum(CONFIG.queue_delay_seconds??CONFIG.launch_rate_interval??15,15))||checked('queue-autoclose-enabled')!==!!CONFIG.auto_close_enabled||!sameNum(saveNumValue('queue-autoclose-minutes',0),savedNum(CONFIG.auto_close_minutes??0,0))||checked('popup-disconnected-enabled')!==(CONFIG.popup_disconnected_enabled!==false)||!sameNum(saveNumValue('popup-scan-interval',30),savedNum(CONFIG.popup_scan_interval_seconds??30,30))||!sameNum(saveNumValue('popup-scan-max-parallel',2),savedNum(CONFIG.popup_scan_max_parallel??2,2));case'performance':return checked('fps-enabled')!==!!PERF.enabled||!sameNum(saveNumValue('fps-limit',240),savedNum(PERF.fps_limit??PERF.framerate_cap??240,240));case'ram':return checked('ram-enabled')!==(CONFIG.roblox_memory_guard_enabled!==false)||!sameNum(currentRamLimit(),normalizeRamLimitValue(CONFIG.roblox_memory_guard_mb??8192));case'graphics':{const graphicsEnabled=!!(GRAPHICS.graphics_low_enabled??GRAPHICS.graphics_auto_enabled);return checked('graphics-auto-enabled')!==graphicsEnabled||!sameNum(saveNumValue('graphics-quality',1),savedNum(GRAPHICS.graphics_quality_level??GRAPHICS.graphics_quality_level_current??1,1))||checked('priority-enabled')!==!!GRAPHICS.auto_process_priority_enabled||valueOf('process-priority')!==String(GRAPHICS.process_priority||'low')}case'window-size':return checked('window-size-enabled')!==!!WINDOW_SIZE.enabled||valueOf('window-size-preset')!==String(WINDOW_SIZE.preset||'640x480')||!sameNum(saveNumValue('window-size-width',640),savedNum(WINDOW_SIZE.width??640,640))||!sameNum(saveNumValue('window-size-height',480),savedNum(WINDOW_SIZE.height??480,480))||checked('window-arrange-enabled')!==!!WINDOW_SIZE.arrange_enabled||!sameNum(saveNumValue('window-arrange-columns',6),savedNum(WINDOW_SIZE.arrange_columns??6,6))||!sameNum(saveNumValue('window-arrange-gap',2),savedNum(WINDOW_SIZE.arrange_gap??2,2));case'cpu-limiter':return checked('cpu-enabled')!==!!CPU_LIMITER.enabled||valueOf('cpu-mode')!==String(CPU_LIMITER.mode||'hard')||!sameNum(saveNumValue('cpu-default-limit',20),savedNum(CPU_LIMITER.default_limit_percent??20,20))||checked('cpu-apply-all')!==(CPU_LIMITER.apply_all!==false)||(!checked('cpu-apply-all')&&!sameCpuRows(cpuRowsFromDom(),cpuRowsFromState()));default:return dirty(view)}}catch(e){return dirty(view)}}
function syncToggleLabels(){document.querySelectorAll('.toggle-row input[type="checkbox"]').forEach(input=>{const text=input.parentElement?.querySelector('span');if(text){text.textContent='';text.hidden=true}})}
function updateSaveState(view){const saveMap={game:'game-save',queue:'queue-save',performance:'fps-save',ram:'ram-save',graphics:'graphics-save','window-size':'window-size-save','cpu-limiter':'cpu-save'},resetMap={game:'game-reset',queue:'queue-reset',performance:'fps-reset',ram:'ram-reset',graphics:'graphics-reset','window-size':'window-size-reset','cpu-limiter':'cpu-reset'},isDirty=dirty(view),save=$(saveMap[view]),reset=$(resetMap[view]);if(save){save.classList.toggle('settings-dirty',isDirty);save.hidden=!isDirty}if(reset)reset.hidden=!isDirty;syncToggleLabels()}
function markDirty(view){if(settingsChanged(view))SETTINGS_DIRTY[view]=true;else delete SETTINGS_DIRTY[view];updateSaveState(view)}
function clearDirty(view){delete SETTINGS_DIRTY[view];updateSaveState(view)}
function unsavedSettings(){return Object.keys(SETTINGS_DIRTY)}
function requireSavedSettings(){const pending=unsavedSettings();if(!pending.length)return true;toast('Save changes first');return false}
function initials(s){return String(s||'?').split(/[^a-zA-Z0-9]+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function cfgFor(user){const key=lower(user);return ACCOUNT_CONFIG.find(a=>lower(a.username)===key)||{}}
function counts(){return countAccounts(ACCOUNTS)}
function filtered(){const rows=filterAccounts(ACCOUNTS,$('account-search')?.value||'',cfgFor);return ACCOUNT_FILTER==='all'?rows:rows.filter(a=>bucket(a)===ACCOUNT_FILTER)}
async function loadAccountsConfig(force=false){if(!force&&Date.now()-configLoadedAt<4000&&ACCOUNT_CONFIG.length)return ACCOUNT_CONFIG;const data=await api('/accounts');if(Array.isArray(data))ACCOUNT_CONFIG=data;configLoadedAt=Date.now();return ACCOUNT_CONFIG}
function accountUserId(a){const cfg=cfgFor(a.username);return String(a.user_id||a.cookie_user_id||cfg.user_id||cfg.cookie_user_id||'').trim()}
function avatarHtml(a,display){const uid=accountUserId(a),src=uid?AVATARS[uid]:'';const fallback=esc(initials(display));if(src)return`<span class="avatar-wrap"><img class="avatar-img" src="${esc(src)}" alt="" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="avatar" hidden>${fallback}</span></span>`;return`<span class="avatar-wrap"><span class="avatar">${fallback}</span></span>`}
async function loadAvatars(){const ids=[...new Set(ACCOUNTS.map(accountUserId).filter(Boolean))].sort();const key=ids.join(',');if(!ids.length||key===avatarLoadedKey)return;avatarLoadedKey=key;const r=await api('/accounts/avatars?user_ids='+encodeURIComponent(key));if(r&&r.avatars)AVATARS={...AVATARS,...r.avatars};renderAccountsTable()}
async function loadConfig(){CONFIG=await api('/config');renderSettings();renderRam();renderWindowSize();const place=CONFIG.game_place_id||placeFromPrivate(CONFIG.game_private_server_url||'');if(place)loadGamePlace(place,true).catch(()=>{});return CONFIG}
async function loadPerformance(){try{PERF=await api('/performance/fps-limiter');renderPerformance();return PERF}catch(e){PERF={ok:false,msg:e.message};renderPerformance();return PERF}}
async function loadGraphics(){try{GRAPHICS=await api('/performance/graphics');renderGraphics();return GRAPHICS}catch(e){GRAPHICS={ok:false,msg:e.message};renderGraphics();return GRAPHICS}}
async function loadWindowSize(){try{WINDOW_SIZE=await api('/performance/window-size');renderWindowSize();return WINDOW_SIZE}catch(e){WINDOW_SIZE={ok:false,msg:e.message};renderWindowSize();return WINDOW_SIZE}}
async function loadCpuLimiter(){try{CPU_LIMITER=await api('/performance/cpu-limiter');renderCpuLimiter();return CPU_LIMITER}catch(e){CPU_LIMITER={ok:false,msg:e.message,rows:[]};renderCpuLimiter();return CPU_LIMITER}}
async function loadTroubleshoot(){try{TROUBLESHOOT=await api('/troubleshoot/roblox-install');renderTroubleshoot();return TROUBLESHOOT}catch(e){TROUBLESHOOT={ok:false,msg:e.message,job:{state:'Failed',progress:e.message}};renderTroubleshoot();return TROUBLESHOOT}}
function resetGameSettings(){return resetGamePanel(panelCtx())}
function resetQueueSettings(){return resetQueuePanel(panelCtx())}
function resetPerformanceSettings(){return resetPerformancePanel(panelCtx())}
function resetRamSettings(){return resetRamPanel(panelCtx())}
function resetGraphicsSettings(){return resetGraphicsPanel(panelCtx())}
function resetWindowSizeSettings(){return resetWindowSizePanel(panelCtx())}
function resetCpuLimiterSettings(){return resetCpuLimiterPanel(panelCtx())}
function robloxInstallConfirm(action){const copy={uninstall:['Uninstall Roblox','Removes all Roblox files from this PC','Uninstall'],latest:['Download latest','Wipes Roblox, then installs latest LIVE player','Download']}[action];if(!copy)return toast('Unknown action');modal(copy[0],`<div class="choice-grid" style="grid-template-columns:1fr"><div class="choice" style="cursor:default">${cardIcon('install')}<strong>${copy[0]}</strong><span class="hint">${copy[1]}</span></div></div>`,`<button class="btn ghost" id="install-back">Back</button><button class="btn ${action==='uninstall'?'danger':'good'}" id="install-confirm">${copy[2]}</button>`);$('install-back').onclick=closeModal;$('install-confirm').onclick=()=>runRobloxInstall(action)}
async function runRobloxInstall(action){try{const path=action==='uninstall'?'/troubleshoot/roblox-install/uninstall':'/troubleshoot/roblox-install/latest';const r=await api(path,'POST',{});closeModal();if(!r.ok)return toast(r.msg||'Install blocked');toast(r.msg||'Job started');await loadTroubleshoot()}catch(e){toast(e.message)}}
let viewSwitchTimer=0,viewEntryTimer=0;
function clearViewAnimationClasses(){document.querySelectorAll('.view.main-view-enter,.view.main-view-leave').forEach(v=>v.classList.remove('main-view-enter','main-view-leave'))}
function animateViewEntry(viewEl){if(!viewEl)return;window.clearTimeout(viewEntryTimer);viewEl.classList.remove('main-view-enter');viewEl.offsetHeight;viewEl.classList.add('main-view-enter');viewEntryTimer=window.setTimeout(()=>viewEl.classList.remove('main-view-enter'),760)}
function activateView(view,animate=true){const next=$('view-'+view),current=document.querySelector('.view.active');if(!next)return;window.clearTimeout(viewSwitchTimer);clearViewAnimationClasses();if(current===next){if(animate)animateViewEntry(next);return}if(!animate||!current){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v===next));if(animate)animateViewEntry(next);return}current.classList.add('main-view-leave');viewSwitchTimer=window.setTimeout(()=>{current.classList.remove('active','main-view-leave');next.classList.add('active');animateViewEntry(next)},150)}
function setView(view){const allowed={accounts:1,game:1,queue:1,performance:1,ram:1,graphics:1,'window-size':1,'cpu-limiter':1,troubleshoot:1},nextView=allowed[view]?view:'accounts',active=$('view-'+nextView)?.classList.contains('active');VIEW=nextView;localStorage.setItem('rg_view',VIEW);document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===VIEW));if(VIEW==='troubleshoot')loadTroubleshoot();if(VIEW==='performance')loadPerformance();if(VIEW==='ram')loadConfig();if(VIEW==='graphics')loadGraphics();if(VIEW==='window-size')loadWindowSize();if(VIEW==='cpu-limiter')loadCpuLimiter();render();activateView(VIEW,!active)}
function render(){ACCOUNTS=Array.isArray(STATUS.accounts)?STATUS.accounts:[];if(!selectedUser&&ACCOUNTS[0])selectedUser=ACCOUNTS[0].username;renderTop();renderAccountsTable();renderSettings();renderPerformance();renderRam();renderGraphics();renderWindowSize();renderCpuLimiter();renderTroubleshoot();syncToggleLabels();Object.keys(SETTINGS_DIRTY).forEach(updateSaveState)}
function renderTop(){const c=counts(),running=!!STATUS.running;$('nav-accounts-count').textContent=c.all;$('h-online').textContent=c.online;$('h-queued').textContent=c.queued;$('h-captcha').textContent=c.captcha;renderAccountFilters(c);syncRunningClock();$('guard-btn').innerHTML=running?`${solarIcon('stopCircle','guard-icon stop')}<span>STOP</span>`:`${solarIcon('play','guard-icon start')}<span>START</span>`;$('guard-btn').className=running?'btn danger guard-action':'btn good guard-action';$('guard-btn').disabled=commandBusy||(!STATUS.can_start&&!STATUS.can_stop)}
function visibleAccountFilters(c=counts()){return c.captcha>0?[...ACCOUNT_FILTERS,'captcha']:ACCOUNT_FILTERS}
function renderAccountFilters(c=counts()){const box=$('account-filters');if(!box)return;const filters=visibleAccountFilters(c);if(!filters.includes(ACCOUNT_FILTER))ACCOUNT_FILTER='all';box.innerHTML=filters.map(key=>`<button class="account-filter ${ACCOUNT_FILTER===key?'active':''}" data-account-filter="${esc(key)}"><span>${esc(bucketLabel(key))}</span><strong>${esc(c[key]??0)}</strong></button>`).join('')}
function setAccountFilter(filter){const filters=visibleAccountFilters();ACCOUNT_FILTER=filters.includes(filter)?filter:'all';localStorage.setItem('rg_account_filter',ACCOUNT_FILTER);renderAccountFilters();renderAccountsTable()}
function renderAccountsTable(){if(document.activeElement?.classList.contains('desc-input'))return;renderAccountFilters();const rows=filtered();$('accounts-table').innerHTML=renderAccountRows({rows,selectedUser,cfgFor,bucket,isBlocked,isCaptcha,rowStatusLabel,rowStatusTitle,avatarHtml,esc})}
function placeFromPrivate(url){const m=String(url||'').match(/roblox\.com\/games\/(\d+)/i);return m?m[1]:''}
function renderGameMap(place='',info=null,msg=''){const card=$('game-map-card');if(!card)return;const id=String(place||'').trim();const data=info||GAME_PLACE_CACHE[id];if(data){card.className='map-card';card.innerHTML=`<img class="map-thumb" src="${esc(data.image_url||'')}" alt=""><div><div class="map-name">${esc(data.name||('Place '+id))}</div><div class="map-byline">${esc(data.builder?('by '+data.builder):'Roblox experience')}</div><div class="map-status">Place ID ${esc(data.place_id||id)}${data.universe_id?' / Universe '+esc(data.universe_id):''}</div></div>`;return}card.className='map-card empty';card.innerHTML=`<div>${esc(msg|| (id?'Click Lookup':'Enter Place ID'))}</div>`}
async function loadGamePlace(place,quiet=false){const id=String(place||'').trim();if(!id){renderGameMap('',null);return null}renderGameMap(id,null,'Loading Roblox map details');const data=await api('/game/place/'+encodeURIComponent(id));GAME_PLACE_CACHE[id]=data;renderGameMap(id,data);if(!quiet)toast(data.name||'place loaded');return data}
function panelCtx(){return{$,api,CONFIG,PERF,GRAPHICS,WINDOW_SIZE,CPU_LIMITER,TROUBLESHOOT,WINDOW_SIZE_PRESETS,dirty,updateSaveState,clearDirty,toast,esc,loadConfig,loadGraphics,manualSnapshot,renderPerformance,renderRam,renderGraphics,renderWindowSize,renderCpuLimiter}}
function renderSettings(){return renderSettingsPanel(panelCtx())}
function renderPerformance(next){if(next)PERF=next;return renderPerformancePanel(panelCtx())}
function renderRam(){return renderRamPanel(panelCtx())}
function renderGraphics(next){if(next)GRAPHICS=next;return renderGraphicsPanel(panelCtx())}
function renderWindowSize(next){if(next)WINDOW_SIZE=next;return renderWindowSizePanel(panelCtx())}
function renderCpuLimiter(next){if(next)CPU_LIMITER=next;return renderCpuLimiterPanel(panelCtx())}
function renderTroubleshoot(){return renderTroubleshootPanel(panelCtx())}
function setStreamState(text,cls='stream'){const state=$('stream-state');if(state){state.textContent=text;state.className=cls}}
const statusRuntime=createStatusRuntime({api,nextSequence:()=>++STATUS_REQUEST_SEQ,acceptStatus,setStreamState,loadAccountsConfig,render,loadAvatars,toast});
async function manualSnapshot(){return statusRuntime.manualSnapshot()}
async function toggleGuard(){if(commandBusy)return;if(!STATUS.running&&!requireSavedSettings())return;commandBusy=true;renderTop();try{const r=await api(STATUS.running?'/stop':'/start','POST');toast(r.msg||'command sent');await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderTop()}}
async function saveAccounts(next,msg='accounts saved'){const r=await api('/accounts','POST',next);if(!r.ok)throw new Error(r.msg||'Save failed');ACCOUNT_CONFIG=next;configLoadedAt=Date.now();toast(msg);await manualSnapshot()}
async function saveDescription(user,value){const current=await loadAccountsConfig(true),key=lower(user);const next=current.map(a=>lower(a.username)===key?{...a,description:value}:a);await saveAccounts(next,'Saved')}
async function reloadCookies(){if(commandBusy)return;commandBusy=true;renderTop();try{const r=await api('/accounts/reload','POST',{});ACCOUNT_CONFIG=[];configLoadedAt=0;toast(r.msg||'Reloaded cookies');await loadAccountsConfig(true);await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderTop()}}
function deleteAccount(user){if(!user)return;const a=ACCOUNTS.find(x=>x.username===user)||{},cfg=cfgFor(user),display=a.display||cfg.alias||user;modal('Delete Account',`<div class="choice-grid" style="grid-template-columns:1fr"><div class="choice" style="cursor:default">${cardIcon('delete')}<strong>Delete <span class="danger-name">${esc(display)}</span></strong><span class="hint">Removes this account and cookie</span></div></div>`,`<button class="btn ghost" id="delete-back">Back</button><button class="btn danger" id="delete-confirm">Delete Account</button>`);$('delete-back').onclick=closeModal;$('delete-confirm').onclick=()=>confirmDeleteAccount(user)}
async function confirmDeleteAccount(user){if(!user)return;commandBusy=true;renderAccountsTable();try{const current=await loadAccountsConfig(true),key=lower(user),next=current.filter(a=>lower(a.username)!==key);await saveAccounts(next,'Deleted');if(lower(selectedUser)===key){selectedUser=next[0]?.username||'';selectedUser?localStorage.setItem('rg_selected',selectedUser):localStorage.removeItem('rg_selected')}closeModal()}catch(e){toast(e.message)}finally{commandBusy=false;renderAccountsTable()}}
async function launchAccount(user){if(!user)return;if(!requireSavedSettings())return;const account=ACCOUNTS.find(a=>a.username===user);if(account&&isCaptcha(account))return toast('Solve CAPTCHA manually, then Resume or Reload Cookies');if(account&&isBlocked(account))return toast(account.blocked_reason||'Reimport correct cookie first');const cfg=cfgFor(user);const body={place_id:cfg.place_id||CONFIG.game_place_id||'',global_vip_link:CONFIG.game_private_server_url||'',auto_create_private_server_enabled:!!CONFIG.auto_create_private_server_enabled,auto_create_private_server_free_only:CONFIG.auto_create_private_server_free_only!==false,multi_roblox:CONFIG.multi_roblox_enabled!==false};try{const r=await api('/account/'+encodeURIComponent(user)+'/launch','POST',body);toast(r.msg||'launch requested');await manualSnapshot()}catch(e){toast(e.message)}}
async function dedupeAccount(user){if(!user)return;try{const r=await api('/account/'+encodeURIComponent(user)+'/kill-duplicate','POST',{});toast('duplicates closed: '+(r.count||0));await manualSnapshot()}catch(e){toast(e.message)}}
async function focusCaptcha(user){if(!user)return;commandBusy=true;renderAccountsTable();try{const r=await api('/account/'+encodeURIComponent(user)+'/captcha/focus','POST',{});toast(r.msg||'Roblox window focused')}catch(e){toast(e.message)}finally{commandBusy=false;renderAccountsTable()}}
async function openCaptchaLogin(user){if(!user)return;commandBusy=true;renderAccountsTable();try{const r=await api('/account/'+encodeURIComponent(user)+'/captcha/open-login','POST',{});toast(r.msg||'Roblox login opened')}catch(e){toast(e.message)}finally{commandBusy=false;renderAccountsTable()}}
async function resumeCaptcha(user){if(!user)return;commandBusy=true;renderAccountsTable();try{const r=await api('/account/'+encodeURIComponent(user)+'/captcha/resume','POST',{});toast(r.msg||'Resume requested');await loadAccountsConfig(true);await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderAccountsTable()}}
function closeAllRoblox(){if(commandBusy)return;modal('Close All Roblox',`<div class="choice-grid" style="grid-template-columns:1fr"><div class="choice" style="cursor:default">${cardIcon('close')}<strong>Close Roblox only</strong><span class="hint">Closes every Roblox window, Cronus stays running</span></div></div>`,`<button class="btn ghost" id="close-all-back">Back</button><button class="btn danger" id="close-all-confirm">Close All Roblox</button>`);$('close-all-back').onclick=closeModal;$('close-all-confirm').onclick=confirmCloseAllRoblox}
async function confirmCloseAllRoblox(){if(commandBusy)return;commandBusy=true;renderTop();try{const r=await api('/roblox/close-all','POST',{});closeModal();toast(r.msg||'Roblox closed');await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderTop()}}
function openAdd(){openCookie()}
function openCookie(){modal('Import Cookies',`<div class="field"><div class="hint">One cookie per line</div><textarea id="cookie-lines" class="textarea" placeholder="Paste cookies here"></textarea></div>`,`<button class="btn ghost" id="cookie-cancel">Cancel</button><button class="btn good" id="cookie-add">Add Accounts</button>`);$('cookie-cancel').onclick=closeModal;$('cookie-add').onclick=submitCookies}
async function submitCookies(){const lines=$('cookie-lines').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const r=await api('/accounts/import','POST',{kind:'cookies',lines});toast(`Imported (${r.imported||0})`);closeModal();await loadAccountsConfig(true);await manualSnapshot()}
async function saveGame(){return saveGamePanel(panelCtx())}
async function lookupGame(){let place=$('game-place').value.trim();const url=$('game-private').value.trim();$('game-lookup-result').textContent='';if(!place&&url){place=placeFromPrivate(url);if(!place){try{const r=await api('/account/_/test-vip','POST',{vip_url:url});if(r.ok&&r.place_id)place=r.place_id;$('game-lookup-result').textContent=r.ok?`VIP link parsed: Place ID ${r.place_id}`:(r.msg||'Invalid URL')}catch(e){$('game-lookup-result').textContent=e.message}}if(place)$('game-place').value=place}if(!place)return toast('Place ID required');try{const data=await loadGamePlace(place,false);$('game-lookup-result').textContent=data?.name?`${data.name} loaded`:'Map loaded'}catch(e){renderGameMap(place,null,e.message);$('game-lookup-result').textContent=e.message}}
async function saveQueue(){return saveQueuePanel(panelCtx())}
async function savePerformance(){PERF=await savePerformancePanel(panelCtx())}
async function saveRam(){CONFIG=await saveRamPanel(panelCtx())}
async function saveGraphics(){GRAPHICS=await saveGraphicsPanel(panelCtx())}
async function saveWindowSize(){WINDOW_SIZE=await saveWindowSizePanel(panelCtx())}
async function saveCpuLimiter(){CPU_LIMITER=await saveCpuLimiterPanel(panelCtx())}
function connectStream(){return statusRuntime.connectStream()}
applySolarStaticIcons(document);
bindDashboardEvents({$,document,syncToggleLabels,setView,toggleGuard,openAdd,reloadCookies,closeAllRoblox,closeModal,renderAccountsTable,setAccountFilter,resetGameSettings,saveGame,lookupGame,resetPerformanceSettings,savePerformance,resetRamSettings,saveRam,resetGraphicsSettings,saveGraphics,resetWindowSizeSettings,saveWindowSize,resetCpuLimiterSettings,saveCpuLimiter,resetQueueSettings,saveQueue,robloxInstallConfirm,markDirty,renderSettings,renderPerformance,renderRam,renderGraphics,renderWindowSize,renderCpuLimiter,gameLookupTimer:()=>gameLookupTimer,setGameLookupTimer:v=>{gameLookupTimer=v},renderGameMap,loadGamePlace,placeFromPrivate,deleteAccount,launchAccount,dedupeAccount,focusCaptcha,openCaptchaLogin,resumeCaptcha,selectUser:user=>{selectedUser=user;localStorage.setItem('rg_selected',selectedUser)},saveDescription,toast});
(async function init(){setView(VIEW);await loadConfig();await loadPerformance();await loadGraphics();await loadWindowSize();await loadCpuLimiter();await loadTroubleshoot();await loadAccountsConfig(true);connectStream();setInterval(renderRunningClock,1000);setInterval(()=>{if(VIEW==='troubleshoot')loadTroubleshoot();if(VIEW==='cpu-limiter')loadCpuLimiter()},3500)})();
