const $=id=>document.getElementById(id);
let STATUS={},ACCOUNTS=[],ACCOUNT_CONFIG=[],CONFIG={},PERF={},GRAPHICS={},WINDOW_SIZE={},CPU_LIMITER={},TROUBLESHOOT={},GAME_PLACE_CACHE={},AVATARS={},avatarLoadedKey='',VIEW=localStorage.getItem('rg_view')||'accounts',selectedUser=localStorage.getItem('rg_selected')||'',commandBusy=false,configLoadedAt=0,gameLookupTimer=0,LAST_STATUS_REVISION=-1,LAST_STATUS_UPDATED_AT=0,STATUS_REQUEST_SEQ=0,STATUS_APPLIED_SEQ=0,SETTINGS_DIRTY={},RUNNING_CLOCK_ACTIVE=false,RUNNING_CLOCK_BASE_SECONDS=0,RUNNING_CLOCK_BASE_MS=Date.now();
const WINDOW_SIZE_PRESETS={'320x240':[320,240],'480x360':[480,360],'640x480':[640,480],'800x600':[800,600],'1024x768':[1024,768],'1280x720':[1280,720],'1600x900':[1600,900],'1920x1080':[1920,1080]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lower=s=>String(s||'').toLowerCase();
const num=v=>Number(v||0)||0;
function uptimeSeconds(value){if(typeof value==='number')return Math.max(0,Math.floor(value));const s=String(value||'').trim();if(!s)return 0;const parts=s.split(':').map(x=>Number(x)||0);if(parts.length===3)return parts[0]*3600+parts[1]*60+parts[2];if(parts.length===2)return parts[0]*60+parts[1];return Number(s)||0}
function shortDuration(seconds){let s=Math.max(0,Math.floor(seconds||0)),h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60),r=s%60;if(h)return `${h}h ${m}m`;if(m)return `${m}m ${r}s`;return `${r}s`}
function syncRunningClock(){RUNNING_CLOCK_ACTIVE=!!STATUS.running;RUNNING_CLOCK_BASE_SECONDS=RUNNING_CLOCK_ACTIVE?uptimeSeconds(STATUS.uptime):0;RUNNING_CLOCK_BASE_MS=Date.now();renderRunningClock()}
function renderRunningClock(){const el=$('h-running-time');if(!el)return;const elapsed=RUNNING_CLOCK_ACTIVE?RUNNING_CLOCK_BASE_SECONDS+Math.floor((Date.now()-RUNNING_CLOCK_BASE_MS)/1000):0;el.textContent=`Running: ${shortDuration(elapsed)}`}
function apiToken(){return document.querySelector('meta[name="argus-api-token"]')?.content||''}
async function api(path,method='GET',body){const opt={method,headers:{}};if(method&&String(method).toUpperCase()!=='GET'){const token=apiToken();if(token)opt.headers['X-Argus-Token']=token}if(body!==undefined){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(body)}const r=await fetch('/api'+path,opt);let data={};try{data=await r.json()}catch(e){}if(!r.ok)throw new Error(data.detail||data.msg||r.statusText);return data}
function acceptStatus(nextStatus,seq=0){const rev=Number(nextStatus?.status_revision??-1),updated=Number(nextStatus?.status_updated_at??0);if(seq&&seq<STATUS_APPLIED_SEQ)return false;if(rev>=0&&LAST_STATUS_REVISION>rev){if(updated&&updated>LAST_STATUS_UPDATED_AT){LAST_STATUS_REVISION=-1}else{return false}}if(seq)STATUS_APPLIED_SEQ=seq;if(rev>=0)LAST_STATUS_REVISION=rev;if(updated)LAST_STATUS_UPDATED_AT=updated;STATUS=nextStatus||{};return true}
function toast(msg){const el=$('toast');el.innerHTML=`<span class="toast-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg></span><span class="toast-text">${esc(msg)}</span><button class="toast-close" aria-label="Close notification">&times;</button>`;el.classList.add('show');const close=el.querySelector('.toast-close');if(close)close.onclick=()=>{el.classList.remove('show');clearTimeout(toast.t)};clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3200)}
function dirty(view){return !!SETTINGS_DIRTY[view]}
function syncToggleLabels(){document.querySelectorAll('.toggle-row input[type="checkbox"]').forEach(input=>{const text=input.parentElement?.querySelector('span');if(text)text.textContent=input.checked?'Enabled':'Disabled'})}
function setCompactToggle(inputId,labelId,controlsId,onLabel){const enabled=!!$(inputId)?.checked,label=$(labelId),controls=$(controlsId);if(label)label.textContent=enabled?onLabel:'Disabled';if(controls)controls.hidden=!enabled;return enabled}
function updateSaveState(view){const saveMap={game:'game-save',queue:'queue-save',performance:'fps-save',graphics:'graphics-save','window-size':'window-size-save','cpu-limiter':'cpu-save'},resetMap={game:'game-reset',queue:'queue-reset',performance:'fps-reset',graphics:'graphics-reset','window-size':'window-size-reset','cpu-limiter':'cpu-reset'},isDirty=dirty(view),save=$(saveMap[view]),reset=$(resetMap[view]);if(save){save.classList.toggle('settings-dirty',isDirty);save.hidden=!isDirty}if(reset)reset.hidden=!isDirty;syncToggleLabels()}
function markDirty(view){SETTINGS_DIRTY[view]=true;updateSaveState(view)}
function clearDirty(view){delete SETTINGS_DIRTY[view];updateSaveState(view)}
function clearDirtyMany(...views){views.forEach(clearDirty)}
function unsavedSettings(){return Object.keys(SETTINGS_DIRTY)}
function requireSavedSettings(){const pending=unsavedSettings();if(!pending.length)return true;toast('Save changes first.');return false}
function initials(s){return String(s||'?').split(/[^a-zA-Z0-9]+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function cfgFor(user){const key=lower(user);return ACCOUNT_CONFIG.find(a=>lower(a.username)===key)||{}}
function selected(){return ACCOUNTS.find(a=>a.username===selectedUser)||ACCOUNTS[0]||null}
function isBlocked(a){return a.launchable===false||!!a.blocked_reason||!!a.cookie_mismatch}
function blockedStatusLabel(a){const reason=lower(a?.blocked_reason||a?.manual_status||a?.last_recovery_reason||a?.last_state_reason||'');if(reason.includes('multi_roblox_guard_failed')||reason.includes('multi roblox guard'))return'Guard Failed';if(reason.includes('cookie_mismatch')||reason.includes('cookie mismatch')||reason.includes('cookie belongs'))return'Cookie Mismatch';if(reason.includes('cookie')&&(reason.includes('invalid')||reason.includes('expired')||reason.includes('authenticated')))return'Invalid Cookie';return'Blocked'}
function isNetworkIssue(a){const st=String(a?.public_state||a?.state||'').toUpperCase(),rs=String(a?.runtime_state||'').toUpperCase(),live=lower(a?.liveness_state),rec=lower(a?.recovery_status||''),text=lower([a?.recovery_status,a?.last_recovery_reason,a?.last_state_reason,a?.last_crash_reason,a?.watchdog_classification,a?.presence_disconnect_reason,a?.health_flags].filter(Boolean).join(' ')),active=['NETWORK_LOST','COOLDOWN','RECOVERING'].includes(st)||['RECOVERING','BACKOFF'].includes(rs),popupText=rec.includes('checking_disconnect')||text.includes('disconnect_dialog')||text.includes('session_conflict')||text.includes('error 273')||text.includes('code 273'),netText=popupText||text.includes('network_lost')||text.includes('network lost')||text.includes('network_drop')||text.includes('network drop')||text.includes('connection_error')||text.includes('connection error')||text.includes('disconnected')||text.includes('disconnect')||text.includes('error 277')||text.includes('code 277')||text.includes('presence_not_ingame'),presenceDown=num(a?.presence_disconnect_for)>0&&netText;return st==='NETWORK_LOST'||live==='reconnecting'||popupText||presenceDown||(active&&netText)}
function isStableInGame(a){const st=String(a?.public_state||a?.state||'').toUpperCase(),rs=String(a?.runtime_state||'').toUpperCase(),rec=lower(a?.recovery_status||''),cmd=lower(a?.command_inflight?.action||a?.command_inflight||''),detail=lower([a?.recovery_status,a?.last_recovery_reason,a?.last_state_reason,a?.last_crash_reason,a?.watchdog_classification,a?.presence_disconnect_reason,a?.health_flags,a?.recovery_step].filter(Boolean).join(' ')),unstable=rec.includes('recover')||rec.includes('checking_disconnect')||detail.includes('session_conflict')||detail.includes('connection_error')||detail.includes('disconnect_dialog')||detail.includes('visual_disconnect')||detail.includes('disconnected')||detail.includes('error 273')||detail.includes('code 273')||detail.includes('error 277')||detail.includes('code 277')||detail.includes('security_kick')||detail.includes('unexpected_client_behavior');return !!a?.pid&&a?.process_alive!==false&&(st==='IN_GAME'||rs==='RUNNING')&&!cmd&&!unstable&&!['NETWORK_LOST','COOLDOWN','FAILED','CRASH'].includes(st)}
function bucket(a){if(isBlocked(a))return'blocked';const st=String(a.public_state||a.state||'').toUpperCase(),rs=String(a.runtime_state||'').toUpperCase();if(isStableInGame(a))return'online';if(isNetworkIssue(a))return'network';if(st==='IN_GAME'||rs==='RUNNING'&&a.pid)return'online';if(st==='QUEUED')return'queued';if(st==='IDLE'||st==='READY'||rs==='STOPPED')return'idled';if(st==='COOLDOWN')return'cooldown';if(st==='FAILED'||st==='CRASH')return'finished';if(['LAUNCHING','VERIFY','NETWORK_LOST'].includes(st)||lower(a.recovery_status).includes('recover'))return'recovery';return'queued'}
function label(b){return{all:'All',online:'In Game',queued:'Queued',idled:'Idle',finished:'Failed',blocked:'Blocked',banned:'Banned',locked:'Locked',recovery:'Recovering',captcha:'Captcha',cooldown:'Cooldown',network:'Disconnected'}[b]||'Queued'}
function counts(){const out={all:ACCOUNTS.length,online:0,queued:0,idled:0,finished:0,blocked:0,banned:0,locked:0,recovery:0,captcha:0,cooldown:0,network:0};ACCOUNTS.forEach(a=>out[bucket(a)]++);return out}
function filtered(){const q=lower($('account-search')?.value||'');return ACCOUNTS.filter(a=>{if(!q)return true;const cfg=cfgFor(a.username);return lower([a.username,a.display,cfg.alias,a.description,cfg.description,a.state,a.pid].join(' ')).includes(q)})}
async function loadAccountsConfig(force=false){if(!force&&Date.now()-configLoadedAt<4000&&ACCOUNT_CONFIG.length)return ACCOUNT_CONFIG;const data=await api('/accounts');if(Array.isArray(data))ACCOUNT_CONFIG=data;configLoadedAt=Date.now();return ACCOUNT_CONFIG}
function accountUserId(a){const cfg=cfgFor(a.username);return String(a.user_id||a.cookie_user_id||cfg.user_id||cfg.cookie_user_id||'').trim()}
function avatarHtml(a,display){const uid=accountUserId(a),src=uid?AVATARS[uid]:'';const fallback=esc(initials(display));if(src)return`<span class="avatar-wrap"><img class="avatar-img" src="${esc(src)}" alt="" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="avatar" hidden>${fallback}</span></span>`;return`<span class="avatar-wrap"><span class="avatar">${fallback}</span></span>`}
async function loadAvatars(){const ids=[...new Set(ACCOUNTS.map(accountUserId).filter(Boolean))].sort();const key=ids.join(',');if(!ids.length||key===avatarLoadedKey)return;avatarLoadedKey=key;const r=await api('/accounts/avatars?user_ids='+encodeURIComponent(key));if(r&&r.avatars)AVATARS={...AVATARS,...r.avatars};renderAccountsTable()}
async function loadConfig(){CONFIG=await api('/config');renderSettings();renderWindowSize();const place=CONFIG.game_place_id||placeFromPrivate(CONFIG.game_private_server_url||'');if(place)loadGamePlace(place,true).catch(()=>{});return CONFIG}
async function loadPerformance(){try{PERF=await api('/performance/fps-limiter');renderPerformance();return PERF}catch(e){PERF={ok:false,msg:e.message};renderPerformance();return PERF}}
async function loadGraphics(){try{GRAPHICS=await api('/performance/graphics');renderGraphics();return GRAPHICS}catch(e){GRAPHICS={ok:false,msg:e.message};renderGraphics();return GRAPHICS}}
async function loadWindowSize(){try{WINDOW_SIZE=await api('/performance/window-size');renderWindowSize();return WINDOW_SIZE}catch(e){WINDOW_SIZE={ok:false,msg:e.message};renderWindowSize();return WINDOW_SIZE}}
async function loadCpuLimiter(){try{CPU_LIMITER=await api('/performance/cpu-limiter');renderCpuLimiter();return CPU_LIMITER}catch(e){CPU_LIMITER={ok:false,msg:e.message,rows:[]};renderCpuLimiter();return CPU_LIMITER}}
async function loadTroubleshoot(){try{TROUBLESHOOT=await api('/troubleshoot/roblox-install');renderTroubleshoot();return TROUBLESHOOT}catch(e){TROUBLESHOOT={ok:false,msg:e.message,job:{state:'Failed',progress:e.message}};renderTroubleshoot();return TROUBLESHOOT}}
function resetGameSettings(){clearDirty('game');renderSettings()}
function resetQueueSettings(){clearDirty('queue');renderSettings()}
function resetPerformanceSettings(){clearDirty('performance');renderPerformance()}
function resetGraphicsSettings(){clearDirty('graphics');renderGraphics()}
function resetWindowSizeSettings(){clearDirty('window-size');renderWindowSize()}
function resetCpuLimiterSettings(){clearDirty('cpu-limiter');renderCpuLimiter()}
function robloxInstallConfirm(action){const copy={uninstall:['Uninstall Roblox','Removes all Roblox files from this PC.','Uninstall'],latest:['Download latest','Wipes Roblox, then installs latest LIVE player.','Download']}[action];if(!copy)return toast('Unknown action');modal(copy[0],`<div class="choice-grid" style="grid-template-columns:1fr"><div class="choice" style="cursor:default">${cardIcon('install')}<strong>${copy[0]}</strong><span class="hint">${copy[1]}</span></div></div>`,`<button class="btn ghost" id="install-back">Back</button><button class="btn ${action==='uninstall'?'danger':'good'}" id="install-confirm">${copy[2]}</button>`);$('install-back').onclick=closeModal;$('install-confirm').onclick=()=>runRobloxInstall(action)}
async function runRobloxInstall(action){try{const path=action==='uninstall'?'/troubleshoot/roblox-install/uninstall':'/troubleshoot/roblox-install/latest';const r=await api(path,'POST',{});closeModal();if(!r.ok)return toast(r.msg||'Install blocked');toast(r.msg||'Job started');await loadTroubleshoot()}catch(e){toast(e.message)}}
function setView(view){const allowed={accounts:1,game:1,queue:1,performance:1,graphics:1,'window-size':1,'cpu-limiter':1,troubleshoot:1};VIEW=allowed[view]?view:'accounts';localStorage.setItem('rg_view',VIEW);document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+VIEW));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===VIEW));if(VIEW==='troubleshoot')loadTroubleshoot();if(VIEW==='performance')loadPerformance();if(VIEW==='graphics')loadGraphics();if(VIEW==='window-size')loadWindowSize();if(VIEW==='cpu-limiter')loadCpuLimiter();render()}
function render(){ACCOUNTS=Array.isArray(STATUS.accounts)?STATUS.accounts:[];if(!selectedUser&&ACCOUNTS[0])selectedUser=ACCOUNTS[0].username;renderTop();renderAccountsTable();renderSettings();renderPerformance();renderGraphics();renderWindowSize();renderCpuLimiter();renderTroubleshoot();syncToggleLabels();Object.keys(SETTINGS_DIRTY).forEach(updateSaveState)}
function renderTop(){const c=counts(),running=!!STATUS.running;$('nav-accounts-count').textContent=c.all;$('h-online').textContent=c.online;$('h-queued').textContent=c.queued;syncRunningClock();$('guard-btn').innerHTML=running?'<svg class="guard-icon stop" aria-hidden="true" viewBox="0 0 24 24"><rect x="7" y="7" width="10" height="10" rx="1.5"/></svg><span>STOP</span>':'<svg class="guard-icon" aria-hidden="true" viewBox="0 0 24 24"><path d="M7 5v14l11-7z"/></svg><span>START</span>';$('guard-btn').className=running?'btn danger guard-action':'btn good guard-action';$('guard-btn').disabled=commandBusy||(!STATUS.can_start&&!STATUS.can_stop)}
function rowStatusLabel(a,b){if(isBlocked(a))return blockedStatusLabel(a);const st=String(a.public_state||a.state||'').toUpperCase(),rs=String(a.runtime_state||'').toUpperCase(),cmd=lower(a.command_inflight?.action||a.command_inflight||''),rec=lower(a.recovery_status||''),detail=lower([a?.recovery_status,a?.last_recovery_reason,a?.last_state_reason,a?.last_crash_reason,a?.watchdog_classification,a?.presence_disconnect_reason,a?.health_flags,a?.recovery_step].filter(Boolean).join(' ')),apiLabel=String(a.state_label||'').trim(),step=lower(a.recovery_step||'');if(apiLabel==='Checking Disconnect'||apiLabel==='Rejoining')return apiLabel;if(rec.includes('checking_disconnect')||step.includes('checking disconnect'))return'Checking Disconnect';if(step.includes('rejoining')||step.includes('session reconnect')||step.includes('network rejoin')||step.includes('killing process'))return'Rejoining';if(cmd.includes('launch'))return'Launching';if(cmd.includes('rejoin'))return'Rejoining';if(detail.includes('273')||detail.includes('session_conflict'))return'Session Reconnect';if(detail.includes('267')||detail.includes('268')||detail.includes('security_kick')||detail.includes('unexpected_client_behavior'))return'Rejoining';if(detail.includes('277')||detail.includes('connection_error')||detail.includes('visual_disconnect')||detail.includes('disconnect_dialog')||detail.includes('disconnected'))return rec.includes('recover')||cmd.includes('rejoin')?'Rejoining':'Disconnected';if(isStableInGame(a))return'In Game';if(isNetworkIssue(a))return'Disconnected';if(st==='QUEUED')return'Queued';if(st==='LAUNCHING'||rs==='STARTING')return'Launching';if(st==='VERIFY'||rs==='JOINING')return'Joining Game';if(st==='IN_GAME'||rs==='RUNNING'&&a.pid)return'In Game';if(st==='COOLDOWN'||rs==='BACKOFF')return'Cooldown';if(st==='FAILED')return'Failed';if(st==='CRASH')return'Crashed';if(['IDLE','READY'].includes(st)||rs==='STOPPED')return'Idle';if(st==='RECOVERING'||rs==='RECOVERING'||rec.includes('recover'))return'Recovering';return label(b)}
function rowStatusTitle(a,b){const parts=[rowStatusLabel(a,b)],detail=[a.public_state||a.state||'',a.runtime_state||'',a.recovery_status||'',a.last_recovery_reason||a.last_state_reason||a.last_crash_reason||'',a.liveness_state||''].filter(Boolean).join(' / ');if(detail)parts.push(detail);if(num(a.cooldown_left)>0)parts.push('cooldown '+num(a.cooldown_left)+'s');if(a.pid)parts.push('PID '+a.pid);return parts.join(' - ')}
function renderAccountsTable(){if(document.activeElement?.classList.contains('desc-input'))return;const rows=filtered();$('accounts-table').innerHTML=rows.map((a,i)=>{const cfg=cfgFor(a.username),display=a.display||cfg.alias||a.username,b=bucket(a),desc=a.description??cfg.description??'',blocked=isBlocked(a),reason=a.blocked_reason||'Cookie mismatch';return`<tr class="${a.username===selectedUser?'active':''}" data-user="${esc(a.username)}"><td class="num">${i+1}</td><td><span class="status ${b}" title="${esc(rowStatusTitle(a,b))}">${esc(rowStatusLabel(a,b))}</span></td><td><div class="user">${avatarHtml(a,display)}<div style="min-width:0"><div class="name">${esc(display)}</div><div class="handle">${esc(a.username)}${cfg.cookie_present?' - cookie':''}${a.cookie_username?' - '+esc(a.cookie_username):''}</div>${blocked?`<div class="blocked-note" title="${esc(reason)}">${esc(reason)}</div>`:''}</div></div></td><td><input class="desc-input" data-user="${esc(a.username)}" value="${esc(desc)}" placeholder="Add description"></td><td><div class="row-actions"><button class="icon-btn danger" data-action="delete" data-user="${esc(a.username)}" title="Delete account" aria-label="Delete ${esc(a.username)}">&times;</button></div></td></tr>`}).join('')||'<tr><td colspan="5" style="height:100px;text-align:center;color:var(--muted)">No accounts match the current filter.</td></tr>'}
function placeFromPrivate(url){const m=String(url||'').match(/roblox\.com\/games\/(\d+)/i);return m?m[1]:''}
function renderGameMap(place='',info=null,msg=''){const card=$('game-map-card');if(!card)return;const id=String(place||'').trim();const data=info||GAME_PLACE_CACHE[id];if(data){card.className='map-card';card.innerHTML=`<img class="map-thumb" src="${esc(data.image_url||'')}" alt=""><div><div class="map-name">${esc(data.name||('Place '+id))}</div><div class="map-byline">${esc(data.builder?('by '+data.builder):'Roblox experience')}</div><div class="map-status">Place ID ${esc(data.place_id||id)}${data.universe_id?' / Universe '+esc(data.universe_id):''}</div></div>`;return}card.className='map-card empty';card.innerHTML=`<div>${esc(msg|| (id?'Click Lookup.':'Enter Place ID.'))}</div>`}
async function loadGamePlace(place,quiet=false){const id=String(place||'').trim();if(!id){renderGameMap('',null);return null}renderGameMap(id,null,'Loading Roblox map details...');const data=await api('/game/place/'+encodeURIComponent(id));GAME_PLACE_CACHE[id]=data;renderGameMap(id,data);if(!quiet)toast(data.name||'place loaded');return data}
function renderSettings(){if(!CONFIG)return;const active=document.activeElement?.id||'',gameIds=['game-private','game-place','game-auto-private-enabled','game-multi-roblox'],queueIds=['queue-max','queue-duration','queue-delay','queue-autoclose-enabled','queue-autoclose-minutes','popup-disconnected-enabled','popup-scan-interval','popup-scan-max-parallel','presence-enabled'];if(!dirty('game')&&!gameIds.includes(active)){$('game-private').value=CONFIG.game_private_server_url||'';$('game-place').value=CONFIG.game_place_id||'';$('game-auto-private-enabled').checked=!!CONFIG.auto_create_private_server_enabled;$('game-multi-roblox').checked=CONFIG.multi_roblox_enabled!==false}if(!dirty('queue')&&!queueIds.includes(active)){$('queue-max').value=CONFIG.max_concurrent_accounts??40;$('queue-duration').value=CONFIG.queue_duration_seconds??15;$('queue-delay').value=CONFIG.queue_delay_seconds??CONFIG.launch_rate_interval??15;$('queue-autoclose-enabled').checked=!!CONFIG.auto_close_enabled;$('queue-autoclose-minutes').value=CONFIG.auto_close_minutes??0;$('popup-disconnected-enabled').checked=CONFIG.popup_disconnected_enabled!==false;$('popup-scan-interval').value=CONFIG.popup_scan_interval_seconds??30;$('popup-scan-max-parallel').value=CONFIG.popup_scan_max_parallel??2;$('presence-enabled').checked=!!CONFIG.presence_api_enabled}const popupOn=!!$('popup-disconnected-enabled').checked;setCompactToggle('queue-autoclose-enabled','autoclose-inline-label','autoclose-controls','Every');$('popup-disconnected-controls').hidden=!popupOn;updateSaveState('game');updateSaveState('queue')}
function renderPerformance(){if(!$('fps-enabled'))return;const active=document.activeElement?.id||'';if(!dirty('performance')&&!['fps-enabled','fps-limit'].includes(active)){$('fps-enabled').checked=!!PERF.enabled;$('fps-limit').value=PERF.fps_limit??PERF.framerate_cap??240}setCompactToggle('fps-enabled','fps-inline-label','fps-limit-field','Limit');const notice=$('fps-notice'),msg=PERF.warning||PERF.msg||'';notice.textContent=msg;notice.classList.toggle('show',!!msg&&msg!=='ok');updateSaveState('performance')}
function renderGraphics(){if(!$('graphics-auto-enabled'))return;const active=document.activeElement?.id||'';const graphicsEnabled=!!(GRAPHICS.graphics_low_enabled??GRAPHICS.graphics_auto_enabled);if(!dirty('graphics')&&!['graphics-auto-enabled','graphics-quality','priority-enabled','process-priority'].includes(active)){$('graphics-auto-enabled').checked=graphicsEnabled;$('graphics-quality').value=GRAPHICS.graphics_quality_level??GRAPHICS.graphics_quality_level_current??1;$('priority-enabled').checked=!!GRAPHICS.auto_process_priority_enabled;$('process-priority').value=GRAPHICS.process_priority||'low'}setCompactToggle('graphics-auto-enabled','graphics-quality-label','graphics-quality-controls','Level');$('priority-controls').hidden=!$('priority-enabled').checked;const notice=$('graphics-notice'),msg=GRAPHICS.warning||GRAPHICS.msg||'';notice.textContent=msg;notice.classList.toggle('show',!!msg&&msg!=='ok');updateSaveState('graphics')}
function renderWindowSize(){if(!$('window-size-enabled'))return;const active=document.activeElement?.id||'',ids=['window-size-enabled','window-size-preset','window-size-width','window-size-height','window-arrange-enabled','window-arrange-columns','window-arrange-gap'];if(!dirty('window-size')&&!ids.includes(active)){$('window-size-enabled').checked=!!WINDOW_SIZE.enabled;$('window-size-preset').value=WINDOW_SIZE.preset||'640x480';$('window-size-width').value=WINDOW_SIZE.width??640;$('window-size-height').value=WINDOW_SIZE.height??480;$('window-arrange-enabled').checked=!!WINDOW_SIZE.arrange_enabled;$('window-arrange-columns').value=WINDOW_SIZE.arrange_columns??6;$('window-arrange-gap').value=WINDOW_SIZE.arrange_gap??2}const enabled=!!$('window-size-enabled').checked,preset=$('window-size-preset').value,arrange=!!$('window-arrange-enabled').checked;$('window-size-controls').hidden=!enabled;$('window-size-custom').hidden=!enabled||preset!=='custom';$('window-arrange-controls').hidden=!enabled||!arrange;if(enabled&&preset!=='custom'&&WINDOW_SIZE_PRESETS[preset]&&!['window-size-width','window-size-height'].includes(active)){const pair=WINDOW_SIZE_PRESETS[preset];$('window-size-width').value=pair[0];$('window-size-height').value=pair[1]}const notice=$('window-size-notice'),msg=WINDOW_SIZE.msg||'';notice.textContent=msg;notice.classList.toggle('show',!!msg&&msg!=='ok');updateSaveState('window-size')}
function renderCpuLimiter(){if(!$('cpu-enabled'))return;const active=document.activeElement?.id||'',ids=['cpu-enabled','cpu-mode','cpu-default-limit','cpu-apply-all'];if(!dirty('cpu-limiter')&&!ids.includes(active)&&!active.startsWith('cpu-row-')){$('cpu-enabled').checked=!!CPU_LIMITER.enabled;$('cpu-mode').value=CPU_LIMITER.mode||'hard';$('cpu-default-limit').value=CPU_LIMITER.default_limit_percent??20;$('cpu-apply-all').checked=CPU_LIMITER.apply_all!==false}const enabled=!!$('cpu-enabled').checked,applyAll=!!$('cpu-apply-all').checked,defaultLimit=Number($('cpu-default-limit').value)||Number(CPU_LIMITER.default_limit_percent)||20;$('cpu-controls').hidden=!enabled;const rows=Array.isArray(CPU_LIMITER.rows)?CPU_LIMITER.rows:[];$('cpu-account-rows').innerHTML=rows.map(row=>{const user=row.username||'',disabled=!enabled||applyAll,pid=row.pid||'-',status=row.status||'Pending',msg=row.message||'',rowEnabled=applyAll||!!row.enabled,rowLimit=applyAll?defaultLimit:(row.limit_percent??defaultLimit);return`<tr><td><div class="name">${esc(row.display||user)}</div><div class="handle">${esc(user)}</div></td><td>${esc(pid)}</td><td><input id="cpu-row-enabled-${esc(user)}" class="cpu-row-enabled" data-user="${esc(user)}" type="checkbox" ${rowEnabled?'checked':''} ${disabled?'disabled':''}></td><td><input id="cpu-row-limit-${esc(user)}" class="input cpu-row-limit" data-user="${esc(user)}" type="number" min="5" max="95" step="0.01" value="${esc(Number(rowLimit).toFixed(2))}" ${disabled?'disabled':''}></td><td><strong>${esc(status)}</strong><div class="handle">${esc(msg)}</div></td></tr>`}).join('')||'<tr><td colspan="5" style="height:90px;text-align:center;color:var(--muted)">No accounts.</td></tr>';const notice=$('cpu-notice'),failed=rows.filter(r=>r.status==='Failed').length,fallback=rows.filter(r=>r.status==='Fallback').length,msg=CPU_LIMITER.msg||(failed?`${failed} failed`:fallback?`${fallback} fallback`:'');notice.textContent=msg;notice.classList.toggle('show',!!msg);updateSaveState('cpu-limiter')}
function renderTroubleshoot(){if(!$('roblox-installed-version'))return;const installed=TROUBLESHOOT.installed||{},job=TROUBLESHOOT.job||{},blocked=!!TROUBLESHOOT.running_blocked,active=!!job.active;$('roblox-installed-version').textContent=installed.installed?(installed.version||'Installed'):'Not installed';$('roblox-install-state').textContent=job.state||'Ready';$('roblox-install-progress').textContent=job.progress||job.msg||'-';const notice=$('roblox-install-notice'),msg=TROUBLESHOOT.msg||job.error||job.msg||'';notice.textContent=blocked?(TROUBLESHOOT.block_msg||'Stop Argus and close Roblox first.'):msg;notice.classList.toggle('show',blocked||!!(job.error||TROUBLESHOOT.msg));['roblox-uninstall','roblox-latest'].forEach(id=>{if($(id))$(id).disabled=blocked||active})}
function logTime(ts){if(!ts)return'--:--:--';return new Date(Number(ts)*1000).toLocaleTimeString('en-GB',{hour12:false})}
function logAccountName(e){const p=e?.payload||{};return String(e?.account||p.account||p.account_id||p.display||'System')}
function logSummaryCounts(){const out={running:0,verify:0,recovery:0,failed:0};ACCOUNTS.forEach(a=>{const st=String(a.public_state||a.state||'').toUpperCase(),rs=String(a.runtime_state||'').toUpperCase(),b=bucket(a);if(st==='IN_GAME'||rs==='RUNNING')out.running++;if(['VERIFY','LAUNCHING'].includes(st)||['JOINING','STARTING'].includes(rs))out.verify++;if(['NETWORK_LOST','COOLDOWN'].includes(st)||['RECOVERING','BACKOFF'].includes(rs)||['network','recovery','cooldown'].includes(b))out.recovery++;if(['FAILED','CRASH'].includes(st)||['blocked','finished'].includes(b))out.failed++});return out}
function renderLogSummary(){const c=logSummaryCounts();[['running',c.running],['verify',c.verify],['recovery',c.recovery],['failed',c.failed]].forEach(([k,v])=>{const el=$('log-sum-'+k);if(el)el.textContent=v})}
function logRawText(e){const p=e?.payload||{};return lower([e?.event_type,e?.reason,p.msg,p.reason,p.step,p.status,p.event_type,p.public_state,p.runtime_state].filter(Boolean).join(' '))}
function normalizeLogEvent(e){const p=e?.payload||{},text=logRawText(e),sev=lower(e?.severity||p.severity||'info'),type=lower(e?.event_type||p.event_type||''),reason=lower(e?.reason||p.reason||''),msg=String(p.msg||'').trim();let kind='info',icon='IN',label='INFO';if(sev.includes('critical')||sev.includes('error')||type.includes('failed')||reason.includes('failed')){kind='error';icon='X';label='ERROR'}else if(sev.includes('warn')||type.includes('reject')||reason.includes('stale')){kind='warn';icon='!';label='WARN'}else if(text.includes('recovery')||text.includes('rejoin')||text.includes('disconnect')||text.includes('cooldown')||text.includes('network')){kind='recovery';icon='RJ';label='RECOVERY'}else if(text.includes('state')||text.includes('transition')){kind='state';icon='ST';label='STATE'}else if(text.includes('launch')){kind='state';icon='LA';label='LAUNCH'}else if(text.includes('verify')||text.includes('join')){kind='state';icon='VF';label='VERIFY'}else if(text.includes('pid')||text.includes('process')||text.includes('bound')||text.includes('binding')){kind='info';icon='PID';label='PROC'}else if(sev.includes('success')||text.includes('in_game')||text.includes('online')){kind='success';icon='OK';label='SUCCESS'}const noise=['owned_mutation','status_revision','revision_bumped','transaction_step','rejoin_transaction_update','heartbeat','auto_window_arrange_cycle','auto_process_priority_applied'].some(x=>text.includes(x));const important=!noise&&(kind!=='info'||['LAUNCH','VERIFY','PROC','STATE','SUCCESS'].includes(label));let title=msg||'';if(!title){const account=logAccountName(e);if(label==='LAUNCH')title=`${account} -> Roblox started`;else if(label==='VERIFY')title=`${account} -> waiting verification`;else if(label==='PROC')title=`PID attached${e?.pid?': '+e.pid:''}`;else if(label==='RECOVERY')title=`${account} -> ${String(e?.reason||p.reason||'recovery').replace(/_/g,' ')}`;else if(label==='STATE'){const old=p.old||p.old_runtime||'',nw=p.new||p.new_runtime||e?.public_state||e?.runtime_state||'';title=old&&nw?`${account}: ${old} -> ${nw}`:`${account} -> state update`}else if(label==='SUCCESS')title=`${account} -> success`;else if(label==='ERROR')title=`${account} -> ${String(e?.reason||p.reason||'error').replace(/_/g,' ')}`;else title=`${account} -> ${String(e?.event_type||p.event_type||'event').replace(/_/g,' ')}`}const sub=[e?.public_state||p.public_state||'',e?.runtime_state||p.runtime_state||'',e?.reason||p.reason||'',e?.pid?`PID ${e.pid}`:''].filter(Boolean).join(' / ');return{event:e,payload:p,id:String(e?.id||`${e?.ts||0}-${type}-${logAccountName(e)}`),kind,icon,label,title,sub,noise,important,account:logAccountName(e),tx:String(e?.rejoin_transaction_id||p.rejoin_transaction_id||p.transaction_id||''),ts:Number(e?.ts||0)}}
function logVisible(n){if(LOG_FILTER==='debug')return true;if(LOG_FILTER==='info')return !n.noise;if(LOG_FILTER==='raw')return false;return n.important}
function renderLogInspector(items){const box=$('logs-inspector');if(!box)return;let selected=items.find(n=>n.id===LOG_SELECTED_ID)||items[items.length-1];if(!selected){box.innerHTML='<div class="log-inspector-empty">Select an event to inspect metadata.</div>';return}LOG_SELECTED_ID=selected.id;const e=selected.event,meta={event_type:e.event_type||'',reason:e.reason||'',account:selected.account,pid:e.pid||'',runtime_state:e.runtime_state||'',public_state:e.public_state||'',runtime_generation:e.runtime_generation||0,recovery_generation:e.recovery_generation||0,command_generation:e.command_generation||0,session_id:e.session_id||'',transaction_id:e.rejoin_transaction_id||'',severity:e.severity||'',payload:e.payload||{}};box.innerHTML=`<div class="log-inspector-title">${esc(selected.label)} metadata</div><div class="log-meta-grid"><div class="log-meta-item"><span>Account</span><strong>${esc(meta.account||'System')}</strong></div><div class="log-meta-item"><span>PID</span><strong>${esc(meta.pid||'-')}</strong></div><div class="log-meta-item"><span>Runtime</span><strong>${esc(meta.runtime_state||'-')}</strong></div><div class="log-meta-item"><span>Public</span><strong>${esc(meta.public_state||'-')}</strong></div></div><pre class="log-json">${esc(JSON.stringify(meta,null,2))}</pre>`}
function renderLogs(){renderLogSummary();document.querySelectorAll('[data-log-filter]').forEach(b=>b.classList.toggle('active',b.dataset.logFilter===LOG_FILTER));const rawMode=LOG_FILTER==='raw',obs=$('log-observability'),raw=$('logs-raw'),timeline=$('logs-timeline');if(obs)obs.hidden=rawMode;if(raw)raw.hidden=!rawMode;if(rawMode){$('logbox').innerHTML=(LOGS.length?LOGS:['No raw log lines yet.']).map(line=>`<div class="log-line">${esc(line)}</div>`).join('');return}if(!timeline)return;const items=RUNTIME_EVENTS.slice().sort((a,b)=>(Number(a.ts||0)-Number(b.ts||0))).map(normalizeLogEvent).filter(logVisible).slice(-220);if(!items.length){timeline.innerHTML='<div class="log-inspector-empty" style="padding:14px">No important runtime events yet.</div>';renderLogInspector([]);return}const groups=[];items.forEach(n=>{const key=n.account+'|'+(n.tx||'runtime');let g=groups.find(x=>x.key===key);if(!g){const account=ACCOUNTS.find(a=>lower(a.username)===lower(n.account)||lower(a.display)===lower(n.account));g={key,account:n.account,state:account?rowStatusLabel(account,bucket(account)):(n.event.public_state||n.event.runtime_state||''),items:[]};groups.push(g)}g.items.push(n)});timeline.innerHTML=groups.map(g=>`<section class="log-group"><div class="log-group-head"><div class="log-group-name">${esc(g.account||'System')}</div><div class="log-group-state">${esc(g.state||'Runtime')}</div></div>${g.items.map(n=>`<div class="log-event event-${n.kind} ${n.id===LOG_SELECTED_ID?'selected':''}" data-event-id="${esc(n.id)}"><div class="log-time">${esc(logTime(n.ts))}</div><div class="log-icon">${esc(n.icon)}</div><div><div class="log-event-title">[${esc(n.label)}] ${esc(n.title)}</div><div class="log-event-sub">${esc(n.sub||'metadata hidden')}</div></div></div>`).join('')}</section>`).join('');renderLogInspector(items)}
function setStreamState(text,cls='stream'){const state=$('stream-state');if(state){state.textContent=text;state.className=cls}}
async function manualSnapshot(){const seq=++STATUS_REQUEST_SEQ;try{const nextStatus=await api('/status');if(!acceptStatus(nextStatus,seq))return;setStreamState('synced','stream online');await loadAccountsConfig();render();loadAvatars().catch(()=>{})}catch(e){toast(e.message)}}
async function toggleGuard(){if(commandBusy)return;if(!STATUS.running&&!requireSavedSettings())return;commandBusy=true;renderTop();try{const r=await api(STATUS.running?'/stop':'/start','POST');toast(r.msg||'command sent');await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderTop()}}
async function saveAccounts(next,msg='accounts saved'){const r=await api('/accounts','POST',next);if(!r.ok)throw new Error(r.msg||'Save failed');ACCOUNT_CONFIG=next;configLoadedAt=Date.now();toast(msg);await manualSnapshot()}
async function saveDescription(user,value){const current=await loadAccountsConfig(true),key=lower(user);const next=current.map(a=>lower(a.username)===key?{...a,description:value}:a);await saveAccounts(next,'Saved')}
async function reloadCookies(){if(commandBusy)return;commandBusy=true;renderTop();try{const r=await api('/accounts/reload','POST',{});ACCOUNT_CONFIG=[];configLoadedAt=0;toast(r.msg||'Reloaded cookies');await loadAccountsConfig(true);await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderTop()}}
function deleteAccount(user){if(!user)return;const a=ACCOUNTS.find(x=>x.username===user)||{},cfg=cfgFor(user),display=a.display||cfg.alias||user;modal('Delete Account',`<div class="choice-grid" style="grid-template-columns:1fr"><div class="choice" style="cursor:default">${cardIcon('delete')}<strong>Delete <span class="danger-name">${esc(display)}</span></strong><span class="hint">Removes this account and cookie.</span></div></div>`,`<button class="btn ghost" id="delete-back">Back</button><button class="btn danger" id="delete-confirm">Delete Account</button>`);$('delete-back').onclick=closeModal;$('delete-confirm').onclick=()=>confirmDeleteAccount(user)}
async function confirmDeleteAccount(user){if(!user)return;commandBusy=true;renderAccountsTable();try{const current=await loadAccountsConfig(true),key=lower(user),next=current.filter(a=>lower(a.username)!==key);await saveAccounts(next,'Deleted');if(lower(selectedUser)===key){selectedUser=next[0]?.username||'';selectedUser?localStorage.setItem('rg_selected',selectedUser):localStorage.removeItem('rg_selected')}closeModal()}catch(e){toast(e.message)}finally{commandBusy=false;renderAccountsTable()}}
async function launchAccount(user){if(!user)return;if(!requireSavedSettings())return;const account=ACCOUNTS.find(a=>a.username===user);if(account&&isBlocked(account))return toast(account.blocked_reason||'Reimport correct cookie first');const cfg=cfgFor(user);const body={place_id:cfg.place_id||CONFIG.game_place_id||'',global_vip_link:CONFIG.game_private_server_url||'',auto_create_private_server_enabled:!!CONFIG.auto_create_private_server_enabled,auto_create_private_server_free_only:CONFIG.auto_create_private_server_free_only!==false,multi_roblox:CONFIG.multi_roblox_enabled!==false};try{const r=await api('/account/'+encodeURIComponent(user)+'/launch','POST',body);toast(r.msg||'launch requested');await manualSnapshot()}catch(e){toast(e.message)}}
async function dedupeAccount(user){if(!user)return;try{const r=await api('/account/'+encodeURIComponent(user)+'/kill-duplicate','POST',{});toast('duplicates closed: '+(r.count||0));await manualSnapshot()}catch(e){toast(e.message)}}
function closeAllRoblox(){if(commandBusy)return;modal('Close All Roblox',`<div class="choice-grid" style="grid-template-columns:1fr"><div class="choice" style="cursor:default">${cardIcon('close')}<strong>Close Roblox only</strong><span class="hint">Closes every Roblox window. Argus stays running.</span></div></div>`,`<button class="btn ghost" id="close-all-back">Back</button><button class="btn danger" id="close-all-confirm">Close All Roblox</button>`);$('close-all-back').onclick=closeModal;$('close-all-confirm').onclick=confirmCloseAllRoblox}
async function confirmCloseAllRoblox(){if(commandBusy)return;commandBusy=true;renderTop();try{const r=await api('/roblox/close-all','POST',{});closeModal();toast(r.msg||'Roblox closed');await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderTop()}}
async function verifyAccount(user){if(!user)return;if(!confirm('Verify and finish '+user+'?'))return;commandBusy=true;renderAccountsTable();try{const r=await api('/account/'+encodeURIComponent(user)+'/verify','POST');toast(r.msg||'verified');await loadAccountsConfig(true);await manualSnapshot()}catch(e){toast(e.message)}finally{commandBusy=false;renderAccountsTable()}}
function modal(title,body,foot){$('modal-title').textContent=title;$('modal-body').innerHTML=body;$('modal-foot').innerHTML=foot;$('modal-backdrop').hidden=false}
function closeModal(){$('modal-backdrop').hidden=true}
function cardIcon(type){const icons={cookie:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="8"/><circle cx="9" cy="9" r="1"/><circle cx="14.5" cy="10.5" r="1"/><circle cx="11" cy="15" r="1"/><path d="M15.5 16.5h.01"/></svg>',delete:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 6h18"/><path d="M8 6V4h8v2"/><path d="M19 6l-1 15H6L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/></svg>',close:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M9 9l6 6"/><path d="M15 9l-6 6"/></svg>',install:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>',log:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 4h14v16H5z"/><path d="M8 8h8"/><path d="M8 12h8"/><path d="M8 16h5"/></svg>'};return`<span class="choice-icon">${icons[type]||icons.cookie}</span>`}
function openAdd(){openCookie()}
function openCookie(){modal('Import Cookies',`<div class="field"><div class="hint">One cookie per line.</div><textarea id="cookie-lines" class="textarea" placeholder="user1:pass1:_|WARNING:...&#10;_|WARNING:cookie-only..."></textarea></div>`,`<button class="btn ghost" id="cookie-cancel">Cancel</button><button class="btn good" id="cookie-add">Add Accounts</button>`);$('cookie-cancel').onclick=closeModal;$('cookie-add').onclick=submitCookies}
function parseCookieLine(line){const idx=line.indexOf('_|WARNING:');if(idx>=0)return{username:(line.slice(0,idx).split(':')[0]||'').trim(),cookie:line.slice(idx).trim()};const parts=line.split(':');if(parts.length>=3)return{username:parts[0].trim(),cookie:parts.slice(2).join(':').trim()};return{username:'',cookie:line.trim()}}
async function submitCookies(){const lines=$('cookie-lines').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const r=await api('/accounts/import','POST',{kind:'cookies',lines});toast(`Imported (${r.imported||0})`);closeModal();await loadAccountsConfig(true);await manualSnapshot()}
async function saveGame(){const body={game_private_server_url:$('game-private').value.trim(),game_place_id:$('game-place').value.trim(),auto_create_private_server_enabled:$('game-auto-private-enabled').checked,auto_create_private_server_free_only:true,multi_roblox_enabled:$('game-multi-roblox').checked};const r=await api('/config','POST',body);clearDirty('game');toast('Game saved'+(r.game_defaults_applied?` (${r.game_defaults_applied} defaulted)`:''));await loadConfig();await manualSnapshot()}
async function lookupGame(){let place=$('game-place').value.trim();const url=$('game-private').value.trim();$('game-lookup-result').textContent='';if(!place&&url){place=placeFromPrivate(url);if(!place){try{const r=await api('/account/_/test-vip','POST',{vip_url:url});if(r.ok&&r.place_id)place=r.place_id;$('game-lookup-result').textContent=r.ok?`VIP link parsed: Place ID ${r.place_id}`:(r.msg||'Invalid URL')}catch(e){$('game-lookup-result').textContent=e.message}}if(place)$('game-place').value=place}if(!place)return toast('Place ID required');try{const data=await loadGamePlace(place,false);$('game-lookup-result').textContent=data?.name?`${data.name} loaded`:'Map loaded'}catch(e){renderGameMap(place,null,e.message);$('game-lookup-result').textContent=e.message}}
async function saveQueue(){const body={max_concurrent_accounts:Number($('queue-max').value)||1,queue_duration_seconds:Number($('queue-duration').value)||0,queue_delay_seconds:Number($('queue-delay').value)||0,auto_close_enabled:$('queue-autoclose-enabled').checked,auto_close_minutes:Number($('queue-autoclose-minutes').value)||0,popup_disconnected_enabled:$('popup-disconnected-enabled').checked,popup_scan_interval_seconds:Number($('popup-scan-interval').value)||30,popup_scan_max_parallel:Number($('popup-scan-max-parallel').value)||2,presence_api_enabled:$('presence-enabled').checked,presence_poll_interval_seconds:30,presence_cache_ttl_seconds:30,presence_assist_rejoin_enabled:true};await api('/config','POST',body);clearDirty('queue');toast('Queue saved');await loadConfig();await manualSnapshot()}
async function savePerformance(){const body={enabled:$('fps-enabled').checked,fps_limit:Number($('fps-limit').value)||240};try{PERF=await api('/performance/fps-limiter','POST',body);clearDirty('performance');renderPerformance();toast(PERF.warning||'FPS saved');if(PERF.warning)$('fps-notice').textContent=PERF.warning;await loadConfig();await loadGraphics()}catch(e){$('fps-notice').textContent=e.message;$('fps-notice').classList.add('show');toast(e.message)}}
async function saveGraphics(){const enabled=$('graphics-auto-enabled').checked;const body={graphics_low_enabled:enabled,graphics_auto_enabled:enabled,graphics_quality_level:Number($('graphics-quality').value)||1,auto_process_priority_enabled:$('priority-enabled').checked,process_priority:$('process-priority').value};try{GRAPHICS=await api('/performance/graphics','POST',body);clearDirty('graphics');renderGraphics();toast(GRAPHICS.warning||'Graphics saved');if(GRAPHICS.warning)$('graphics-notice').textContent=GRAPHICS.warning;await loadConfig()}catch(e){$('graphics-notice').textContent=e.message;$('graphics-notice').classList.add('show');toast(e.message)}}
async function saveWindowSize(){const preset=$('window-size-preset').value;const body={enabled:$('window-size-enabled').checked,preset:preset,width:Number($('window-size-width').value)||640,height:Number($('window-size-height').value)||480,arrange_enabled:$('window-arrange-enabled').checked,arrange_columns:Number($('window-arrange-columns').value)||6,arrange_gap:Number($('window-arrange-gap').value)||2};try{WINDOW_SIZE=await api('/performance/window-size','POST',body);clearDirty('window-size');await loadConfig();renderWindowSize();toast(WINDOW_SIZE.msg||'Window size saved')}catch(e){$('window-size-notice').textContent=e.message;$('window-size-notice').classList.add('show');toast(e.message)}}
function collectCpuRows(){if($('cpu-apply-all').checked)return[];return Array.from(document.querySelectorAll('#cpu-account-rows tr')).map(row=>{const enabled=row.querySelector('.cpu-row-enabled'),limit=row.querySelector('.cpu-row-limit'),user=enabled?.dataset.user||limit?.dataset.user||'';return user?{username:user,enabled:!!enabled?.checked,limit_percent:Number(limit?.value)||20}:null}).filter(Boolean)}
async function saveCpuLimiter(){const body={enabled:$('cpu-enabled').checked,mode:$('cpu-mode').value,default_limit_percent:Number($('cpu-default-limit').value)||20,apply_all:$('cpu-apply-all').checked,accounts:collectCpuRows()};try{CPU_LIMITER=await api('/performance/cpu-limiter','POST',body);clearDirty('cpu-limiter');renderCpuLimiter();toast('CPU limiter saved')}catch(e){$('cpu-notice').textContent=e.message;$('cpu-notice').classList.add('show');toast(e.message)}}
function connectStream(){if(!window.EventSource){setStreamState('polling');setInterval(manualSnapshot,1500);manualSnapshot();return}const es=new EventSource('/api/stream');setStreamState('connecting');es.addEventListener('snapshot',async ev=>{const nextStatus=JSON.parse(ev.data);if(!acceptStatus(nextStatus,0))return;setStreamState('live','stream online');await loadAccountsConfig();render();loadAvatars().catch(()=>{})});es.onerror=()=>setStreamState('reconnecting');manualSnapshot();setInterval(manualSnapshot,2500)}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));
document.addEventListener('change',e=>{if(e.target?.matches?.('.toggle-row input[type="checkbox"]'))syncToggleLabels()});
$('guard-btn').onclick=toggleGuard;$('add-btn').onclick=openAdd;$('reload-cookies-btn').onclick=reloadCookies;$('close-all-roblox-btn').onclick=closeAllRoblox;$('modal-close').onclick=closeModal;$('account-search').oninput=renderAccountsTable;$('game-reset').onclick=resetGameSettings;$('game-save').onclick=saveGame;$('game-lookup').onclick=lookupGame;$('fps-reset').onclick=resetPerformanceSettings;$('fps-save').onclick=savePerformance;$('graphics-reset').onclick=resetGraphicsSettings;$('graphics-save').onclick=saveGraphics;$('window-size-reset').onclick=resetWindowSizeSettings;$('window-size-save').onclick=saveWindowSize;$('cpu-reset').onclick=resetCpuLimiterSettings;$('cpu-save').onclick=saveCpuLimiter;$('queue-reset').onclick=resetQueueSettings;$('queue-save').onclick=saveQueue;$('roblox-uninstall').onclick=()=>robloxInstallConfirm('uninstall');$('roblox-latest').onclick=()=>robloxInstallConfirm('latest');
$('game-auto-private-enabled').onchange=()=>{markDirty('game');renderSettings()};$('game-multi-roblox').onchange=()=>{markDirty('game');renderSettings()};$('fps-enabled').onchange=()=>{markDirty('performance');renderPerformance()};$('fps-limit').oninput=()=>markDirty('performance');$('priority-enabled').onchange=()=>{markDirty('graphics');renderGraphics()};$('graphics-auto-enabled').onchange=()=>{markDirty('graphics');renderGraphics()};$('graphics-quality').oninput=()=>markDirty('graphics');$('process-priority').onchange=()=>markDirty('graphics');$('window-size-enabled').onchange=()=>{markDirty('window-size');renderWindowSize()};$('window-size-preset').onchange=()=>{markDirty('window-size');renderWindowSize()};$('window-size-width').oninput=()=>markDirty('window-size');$('window-size-height').oninput=()=>markDirty('window-size');$('window-arrange-enabled').onchange=()=>{markDirty('window-size');renderWindowSize()};$('window-arrange-columns').oninput=()=>markDirty('window-size');$('window-arrange-gap').oninput=()=>markDirty('window-size');$('cpu-enabled').onchange=()=>{markDirty('cpu-limiter');renderCpuLimiter()};$('cpu-mode').onchange=()=>markDirty('cpu-limiter');$('cpu-default-limit').oninput=()=>{markDirty('cpu-limiter');renderCpuLimiter()};$('cpu-apply-all').onchange=()=>{markDirty('cpu-limiter');renderCpuLimiter()};$('cpu-account-rows').addEventListener('input',()=>markDirty('cpu-limiter'));$('cpu-account-rows').addEventListener('change',()=>markDirty('cpu-limiter'));$('queue-autoclose-enabled').onchange=()=>{markDirty('queue');renderSettings()};$('queue-autoclose-minutes').oninput=()=>markDirty('queue');$('popup-disconnected-enabled').onchange=()=>{markDirty('queue');renderSettings()};$('popup-scan-interval').oninput=()=>markDirty('queue');$('popup-scan-max-parallel').oninput=()=>markDirty('queue');$('presence-enabled').onchange=()=>markDirty('queue');$('queue-max').oninput=()=>markDirty('queue');$('queue-duration').oninput=()=>markDirty('queue');$('queue-delay').oninput=()=>markDirty('queue');
$('game-place').addEventListener('input',()=>{markDirty('game');clearTimeout(gameLookupTimer);const place=$('game-place').value.trim();renderGameMap(place);if(/^\d{3,}$/.test(place))gameLookupTimer=setTimeout(()=>loadGamePlace(place,true).catch(e=>renderGameMap(place,null,e.message)),650)});
$('game-private').addEventListener('input',()=>markDirty('game'));
$('game-private').addEventListener('blur',()=>{if($('game-place').value.trim())return;const place=placeFromPrivate($('game-private').value.trim());if(place){$('game-place').value=place;markDirty('game');loadGamePlace(place,true).catch(e=>renderGameMap(place,null,e.message))}});
$('accounts-table').addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(btn){e.stopPropagation();if(btn.dataset.action==='delete')deleteAccount(btn.dataset.user);if(btn.dataset.action==='launch')launchAccount(btn.dataset.user);if(btn.dataset.action==='dedupe')dedupeAccount(btn.dataset.user);return}const row=e.target.closest('tr[data-user]');if(row){selectedUser=row.dataset.user;localStorage.setItem('rg_selected',selectedUser);renderAccountsTable()}});
$('accounts-table').addEventListener('keydown',e=>{if(e.target.classList.contains('desc-input')&&e.key==='Enter'){e.preventDefault();e.target.blur()}});
$('accounts-table').addEventListener('focusout',e=>{if(e.target.classList.contains('desc-input'))saveDescription(e.target.dataset.user,e.target.value).catch(err=>toast(err.message))});
(async function init(){setView(VIEW);await loadConfig();await loadPerformance();await loadGraphics();await loadWindowSize();await loadCpuLimiter();await loadTroubleshoot();await loadAccountsConfig(true);connectStream();setInterval(renderRunningClock,1000);setInterval(()=>{if(VIEW==='troubleshoot')loadTroubleshoot();if(VIEW==='cpu-limiter')loadCpuLimiter()},3500)})();
